#include "guchho/compat.hpp"

namespace guchho::compat {

    const std::unordered_map<std::string_view, JSFeature> StringToJSFeature = {
        {"arbitrary-module-namespace-names",  JSFeature::kArbitraryModuleNamespaceNames},
        {"array-spread",                      JSFeature::kArraySpread},
        {"arrow",                             JSFeature::kArrow},
        {"async-await",                       JSFeature::kAsyncAwait},
        {"async-generator",                   JSFeature::kAsyncGenerator},
        {"bigint",                            JSFeature::kBigint},
        {"class",                             JSFeature::kClass},
        {"class-field",                       JSFeature::kClassField},
        {"class-private-accessor",            JSFeature::kClassPrivateAccessor},
        {"class-private-brand-check",         JSFeature::kClassPrivateBrandCheck},
        {"class-private-field",               JSFeature::kClassPrivateField},
        {"class-private-method",              JSFeature::kClassPrivateMethod},
        {"class-private-static-accessor",     JSFeature::kClassPrivateStaticAccessor},
        {"class-private-static-field",        JSFeature::kClassPrivateStaticField},
        {"class-private-static-method",       JSFeature::kClassPrivateStaticMethod},
        {"class-static-blocks",               JSFeature::kClassStaticBlocks},
        {"class-static-field",                JSFeature::kClassStaticField},
        {"const-and-let",                     JSFeature::kConstAndLet},
        {"decorators",                        JSFeature::kDecorators},
        {"default-argument",                  JSFeature::kDefaultArgument},
        {"destructuring",                     JSFeature::kDestructuring},
        {"dynamic-import",                    JSFeature::kDynamicImport},
        {"exponent-operator",                 JSFeature::kExponentOperator},
        {"export-star-as",                    JSFeature::kExportStarAs},
        {"for-await",                         JSFeature::kForAwait},
        {"for-of",                            JSFeature::kForOf},
        {"from-base64",                       JSFeature::kFromBase64},
        {"function-name-configurable",        JSFeature::kFunctionNameConfigurable},
        {"function-or-class-property-access", JSFeature::kFunctionOrClassPropertyAccess},
        {"generator",                         JSFeature::kGenerator},
        {"hashbang",                          JSFeature::kHashbang},
        {"import-assertions",                 JSFeature::kImportAssertions},
        {"import-attributes",                 JSFeature::kImportAttributes},
        {"import-defer",                      JSFeature::kImportDefer},
        {"import-meta",                       JSFeature::kImportMeta},
        {"import-source",                     JSFeature::kImportSource},
        {"inline-script",                     JSFeature::kInlineScript},
        {"logical-assignment",                JSFeature::kLogicalAssignment},
        {"nested-rest-binding",               JSFeature::kNestedRestBinding},
        {"new-target",                        JSFeature::kNewTarget},
        {"node-colon-prefix-import",          JSFeature::kNodeColonPrefixImport},
        {"node-colon-prefix-require",         JSFeature::kNodeColonPrefixRequire},
        {"nullish-coalescing",                JSFeature::kNullishCoalescing},
        {"object-accessors",                  JSFeature::kObjectAccessors},
        {"object-extensions",                 JSFeature::kObjectExtensions},
        {"object-rest-spread",                JSFeature::kObjectRestSpread},
        {"optional-catch-binding",            JSFeature::kOptionalCatchBinding},
        {"optional-chain",                    JSFeature::kOptionalChain},
        {"regexp-dot-all-flag",               JSFeature::kRegexpDotAllFlag},
        {"regexp-lookbehind-assertions",      JSFeature::kRegexpLookbehindAssertions},
        {"regexp-match-indices",              JSFeature::kRegexpMatchIndices},
        {"regexp-named-capture-groups",       JSFeature::kRegexpNamedCaptureGroups},
        {"regexp-set-notation",               JSFeature::kRegexpSetNotation},
        {"regexp-sticky-and-unicode-flags",   JSFeature::kRegexpStickyAndUnicodeFlags},
        {"regexp-unicode-property-escapes",   JSFeature::kRegexpUnicodePropertyEscapes},
        {"rest-argument",                     JSFeature::kRestArgument},
        {"template-literal",                  JSFeature::kTemplateLiteral},
        {"top-level-await",                   JSFeature::kTopLevelAwait},
        {"typeof-exotic-object-is-object",    JSFeature::kTypeofExoticObjectIsObject},
        {"unicode-escapes",                   JSFeature::kUnicodeEscapes},
        {"using",                             JSFeature::kUsing},
    };

    namespace {

        using EngineVersions = std::unordered_map<Engine, std::vector<VersionRange>>;

        // Key: JSFeature bit value
        const std::unordered_map<JSFeature, EngineVersions> kJsTable = {
            {JSFeature::kArbitraryModuleNamespaceNames, {
                {Engine::kChrome,  {{Version{90, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{87, 0, 0}}}},
                {Engine::kIOS,     {{Version{14, 5, 0}}}},
                {Engine::kNode,    {{Version{16, 0, 0}}}},
                {Engine::kSafari,  {{Version{14, 1, 0}}}},
            }},
            {JSFeature::kArraySpread, {
                {Engine::kChrome,  {{Version{46, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{13, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{36, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{5, 0, 0}}}},
                {Engine::kOpera,   {{Version{33, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kArrow, {
                {Engine::kChrome,  {{Version{49, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{13, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{45, 0, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{6, 0, 0}}}},
                {Engine::kOpera,   {{Version{36, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kAsyncAwait, {
                {Engine::kChrome,  {{Version{55, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{15, 0, 0}}}},
                {Engine::kES,      {{Version{2017, 0, 0}}}},
                {Engine::kFirefox, {{Version{52, 0, 0}}}},
                {Engine::kIOS,     {{Version{11, 0, 0}}}},
                {Engine::kNode,    {{Version{7, 6, 0}}}},
                {Engine::kOpera,   {{Version{42, 0, 0}}}},
                {Engine::kSafari,  {{Version{11, 0, 0}}}},
            }},
            {JSFeature::kAsyncGenerator, {
                {Engine::kChrome,  {{Version{63, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2018, 0, 0}}}},
                {Engine::kFirefox, {{Version{57, 0, 0}}}},
                {Engine::kIOS,     {{Version{12, 0, 0}}}},
                {Engine::kNode,    {{Version{10, 0, 0}}}},
                {Engine::kOpera,   {{Version{50, 0, 0}}}},
                {Engine::kSafari,  {{Version{12, 0, 0}}}},
            }},
            {JSFeature::kBigint, {
                {Engine::kChrome,  {{Version{67, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2020, 0, 0}}}},
                {Engine::kFirefox, {{Version{68, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 12, 0}}}},
                {Engine::kIOS,     {{Version{14, 0, 0}}}},
                {Engine::kNode,    {{Version{10, 4, 0}}}},
                {Engine::kOpera,   {{Version{54, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 7, 14}}}},
                {Engine::kSafari,  {{Version{14, 0, 0}}}},
            }},
            {JSFeature::kClass, {
                {Engine::kChrome,  {{Version{49, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{13, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{45, 0, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{6, 0, 0}}}},
                {Engine::kOpera,   {{Version{36, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kClassField, {
                {Engine::kChrome,  {{Version{73, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{69, 0, 0}}}},
                {Engine::kIOS,     {{Version{14, 0, 0}}}},
                {Engine::kNode,    {{Version{12, 0, 0}}}},
                {Engine::kOpera,   {{Version{60, 0, 0}}}},
                {Engine::kSafari,  {{Version{14, 0, 0}}}},
            }},
            {JSFeature::kClassPrivateAccessor, {
                {Engine::kChrome,  {{Version{84, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{84, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{90, 0, 0}}}},
                {Engine::kIOS,     {{Version{15, 0, 0}}}},
                {Engine::kNode,    {{Version{14, 6, 0}}}},
                {Engine::kOpera,   {{Version{70, 0, 0}}}},
                {Engine::kSafari,  {{Version{15, 0, 0}}}},
            }},
            {JSFeature::kClassPrivateBrandCheck, {
                {Engine::kChrome,  {{Version{91, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 9, 0}}}},
                {Engine::kEdge,    {{Version{91, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{90, 0, 0}}}},
                {Engine::kIOS,     {{Version{15, 0, 0}}}},
                {Engine::kNode,    {{Version{16, 9, 0}}}},
                {Engine::kOpera,   {{Version{77, 0, 0}}}},
                {Engine::kSafari,  {{Version{15, 0, 0}}}},
            }},
            {JSFeature::kClassPrivateField, {
                {Engine::kChrome,  {{Version{84, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{84, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{90, 0, 0}}}},
                {Engine::kIOS,     {{Version{14, 5, 0}}}},
                {Engine::kNode,    {{Version{14, 6, 0}}}},
                {Engine::kOpera,   {{Version{70, 0, 0}}}},
                {Engine::kSafari,  {{Version{14, 1, 0}}}},
            }},
            {JSFeature::kClassPrivateMethod, {
                {Engine::kChrome,  {{Version{84, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{84, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{90, 0, 0}}}},
                {Engine::kIOS,     {{Version{15, 0, 0}}}},
                {Engine::kNode,    {{Version{14, 6, 0}}}},
                {Engine::kOpera,   {{Version{70, 0, 0}}}},
                {Engine::kSafari,  {{Version{15, 0, 0}}}},
            }},
            {JSFeature::kClassPrivateStaticAccessor, {
                {Engine::kChrome,  {{Version{84, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{84, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{90, 0, 0}}}},
                {Engine::kIOS,     {{Version{15, 0, 0}}}},
                {Engine::kNode,    {{Version{14, 6, 0}}}},
                {Engine::kOpera,   {{Version{70, 0, 0}}}},
                {Engine::kSafari,  {{Version{15, 0, 0}}}},
            }},
            {JSFeature::kClassPrivateStaticField, {
                {Engine::kChrome,  {{Version{74, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{90, 0, 0}}}},
                {Engine::kIOS,     {{Version{14, 5, 0}}}},
                {Engine::kNode,    {{Version{12, 0, 0}}}},
                {Engine::kOpera,   {{Version{62, 0, 0}}}},
                {Engine::kSafari,  {{Version{14, 1, 0}}}},
            }},
            {JSFeature::kClassPrivateStaticMethod, {
                {Engine::kChrome,  {{Version{84, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{84, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{90, 0, 0}}}},
                {Engine::kIOS,     {{Version{15, 0, 0}}}},
                {Engine::kNode,    {{Version{14, 6, 0}}}},
                {Engine::kOpera,   {{Version{70, 0, 0}}}},
                {Engine::kSafari,  {{Version{15, 0, 0}}}},
            }},
            {JSFeature::kClassStaticBlocks, {
                {Engine::kChrome,  {{Version{91, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 14, 0}}}},
                {Engine::kEdge,    {{Version{94, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{93, 0, 0}}}},
                {Engine::kIOS,     {{Version{16, 4, 0}}}},
                {Engine::kNode,    {{Version{16, 11, 0}}}},
                {Engine::kOpera,   {{Version{80, 0, 0}}}},
                {Engine::kSafari,  {{Version{16, 4, 0}}}},
            }},
            {JSFeature::kClassStaticField, {
                {Engine::kChrome,  {{Version{73, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{75, 0, 0}}}},
                {Engine::kIOS,     {{Version{14, 5, 0}}}},
                {Engine::kNode,    {{Version{12, 0, 0}}}},
                {Engine::kOpera,   {{Version{60, 0, 0}}}},
                {Engine::kSafari,  {{Version{14, 1, 0}}}},
            }},
            {JSFeature::kConstAndLet, {
                {Engine::kChrome,  {{Version{49, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{14, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{51, 0, 0}}}},
                {Engine::kIOS,     {{Version{11, 0, 0}}}},
                {Engine::kNode,    {{Version{6, 0, 0}}}},
                {Engine::kOpera,   {{Version{36, 0, 0}}}},
                {Engine::kSafari,  {{Version{11, 0, 0}}}},
            }},
            {JSFeature::kDecorators, {}},
            {JSFeature::kDefaultArgument, {
                {Engine::kChrome,  {{Version{49, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{14, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{53, 0, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{6, 0, 0}}}},
                {Engine::kOpera,   {{Version{36, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kDestructuring, {
                {Engine::kChrome,  {{Version{51, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{18, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{53, 0, 0}}}},
                {Engine::kIOS,     {{Version{14, 5, 0}}}},
                {Engine::kNode,    {{Version{6, 5, 0}}}},
                {Engine::kOpera,   {{Version{38, 0, 0}}}},
                {Engine::kSafari,  {{Version{14, 1, 0}}}},
            }},
            {JSFeature::kDynamicImport, {
                {Engine::kChrome,  {{Version{63, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{67, 0, 0}}}},
                {Engine::kIOS,     {{Version{11, 0, 0}}}},
                {Engine::kNode,    {{Version{12, 20, 0}, Version{13, 0, 0}}, {Version{13, 2, 0}, Version{}}}},
                {Engine::kOpera,   {{Version{50, 0, 0}}}},
                {Engine::kSafari,  {{Version{11, 1, 0}}}},
            }},
            {JSFeature::kExponentOperator, {
                {Engine::kChrome,  {{Version{52, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{14, 0, 0}}}},
                {Engine::kES,      {{Version{2016, 0, 0}}}},
                {Engine::kFirefox, {{Version{52, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{10, 3, 0}}}},
                {Engine::kNode,    {{Version{7, 0, 0}}}},
                {Engine::kOpera,   {{Version{39, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 7, 14}}}},
                {Engine::kSafari,  {{Version{10, 1, 0}}}},
            }},
            {JSFeature::kExportStarAs, {
                {Engine::kChrome,  {{Version{72, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2020, 0, 0}}}},
                {Engine::kFirefox, {{Version{80, 0, 0}}}},
                {Engine::kIOS,     {{Version{14, 5, 0}}}},
                {Engine::kNode,    {{Version{13, 2, 0}}}},
                {Engine::kOpera,   {{Version{60, 0, 0}}}},
                {Engine::kSafari,  {{Version{14, 1, 0}}}},
            }},
            {JSFeature::kForAwait, {
                {Engine::kChrome,  {{Version{63, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2018, 0, 0}}}},
                {Engine::kFirefox, {{Version{57, 0, 0}}}},
                {Engine::kIOS,     {{Version{12, 0, 0}}}},
                {Engine::kNode,    {{Version{10, 0, 0}}}},
                {Engine::kOpera,   {{Version{50, 0, 0}}}},
                {Engine::kSafari,  {{Version{12, 0, 0}}}},
            }},
            {JSFeature::kForOf, {
                {Engine::kChrome,  {{Version{51, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{15, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{53, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{6, 5, 0}}}},
                {Engine::kOpera,   {{Version{38, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kFromBase64, {
                {Engine::kChrome,  {{Version{140, 0, 0}}}},
                {Engine::kDeno,    {{Version{2, 5, 0}}}},
                {Engine::kEdge,    {{Version{140, 0, 0}}}},
                {Engine::kFirefox, {{Version{133, 0, 0}}}},
                {Engine::kIOS,     {{Version{18, 2, 0}}}},
                {Engine::kNode,    {{Version{25, 0, 0}}}},
                {Engine::kOpera,   {{Version{124, 0, 0}}}},
                {Engine::kSafari,  {{Version{18, 2, 0}}}},
            }},
            {JSFeature::kFunctionNameConfigurable, {
                {Engine::kChrome,  {{Version{43, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{12, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{38, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{4, 0, 0}}}},
                {Engine::kOpera,   {{Version{30, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 7, 15}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kFunctionOrClassPropertyAccess, {
                {Engine::kChrome,  {{Version{0, 0, 0}}}},
                {Engine::kDeno,    {{Version{0, 0, 0}}}},
                {Engine::kEdge,    {{Version{0, 0, 0}}}},
                {Engine::kES,      {{Version{0, 0, 0}}}},
                {Engine::kFirefox, {{Version{0, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 0, 0}}}},
                {Engine::kIE,      {{Version{0, 0, 0}}}},
                {Engine::kIOS,     {{Version{0, 0, 0}}}},
                {Engine::kNode,    {{Version{0, 0, 0}}}},
                {Engine::kOpera,   {{Version{0, 0, 0}}}},
                {Engine::kRhino,   {{Version{0, 0, 0}}}},
                {Engine::kSafari,  {{Version{16, 3, 0}}}},
            }},
            {JSFeature::kGenerator, {
                {Engine::kChrome,  {{Version{50, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{13, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{53, 0, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{6, 0, 0}}}},
                {Engine::kOpera,   {{Version{37, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kHashbang, {
                {Engine::kChrome,  {{Version{74, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2023, 0, 0}}}},
                {Engine::kFirefox, {{Version{67, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{13, 4, 0}}}},
                {Engine::kNode,    {{Version{12, 0, 0}}}},
                {Engine::kOpera,   {{Version{62, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 7, 15}}}},
                {Engine::kSafari,  {{Version{13, 1, 0}}}},
            }},
            {JSFeature::kImportAssertions, {
                {Engine::kChrome,  {{Version{91, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 17, 0}}}},
                {Engine::kEdge,    {{Version{91, 0, 0}}}},
                {Engine::kNode,    {{Version{16, 14, 0}, Version{22, 0, 0}}}},
            }},
            {JSFeature::kImportAttributes, {
                {Engine::kChrome,  {{Version{123, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 37, 0}}}},
                {Engine::kEdge,    {{Version{123, 0, 0}}}},
                {Engine::kFirefox, {{Version{138, 0, 0}}}},
                {Engine::kIOS,     {{Version{17, 2, 0}}}},
                {Engine::kNode,    {{Version{18, 20, 0}, Version{19, 0, 0}}, {Version{20, 10, 0}, Version{}}}},
                {Engine::kOpera,   {{Version{109, 0, 0}}}},
                {Engine::kSafari,  {{Version{17, 2, 0}}}},
            }},
            {JSFeature::kImportDefer, {}},
            {JSFeature::kImportMeta, {
                {Engine::kChrome,  {{Version{64, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2020, 0, 0}}}},
                {Engine::kFirefox, {{Version{62, 0, 0}}}},
                {Engine::kIOS,     {{Version{12, 0, 0}}}},
                {Engine::kNode,    {{Version{10, 4, 0}}}},
                {Engine::kOpera,   {{Version{51, 0, 0}}}},
                {Engine::kSafari,  {{Version{11, 1, 0}}}},
            }},
            {JSFeature::kImportSource, {}},
            {JSFeature::kInlineScript, {}},
            {JSFeature::kLogicalAssignment, {
                {Engine::kChrome,  {{Version{85, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 2, 0}}}},
                {Engine::kEdge,    {{Version{85, 0, 0}}}},
                {Engine::kES,      {{Version{2021, 0, 0}}}},
                {Engine::kFirefox, {{Version{79, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{14, 0, 0}}}},
                {Engine::kNode,    {{Version{15, 0, 0}}}},
                {Engine::kOpera,   {{Version{71, 0, 0}}}},
                {Engine::kSafari,  {{Version{14, 0, 0}}}},
            }},
            {JSFeature::kNestedRestBinding, {
                {Engine::kChrome,  {{Version{49, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{14, 0, 0}}}},
                {Engine::kES,      {{Version{2016, 0, 0}}}},
                {Engine::kFirefox, {{Version{47, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{10, 3, 0}}}},
                {Engine::kNode,    {{Version{6, 0, 0}}}},
                {Engine::kOpera,   {{Version{36, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 1, 0}}}},
            }},
            {JSFeature::kNewTarget, {
                {Engine::kChrome,  {{Version{46, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{14, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{41, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{5, 0, 0}}}},
                {Engine::kOpera,   {{Version{33, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kNodeColonPrefixImport, {
                {Engine::kES,   {{Version{0, 0, 0}}}},
                {Engine::kNode, {{Version{12, 20, 0}, Version{13, 0, 0}}, {Version{14, 13, 1}, Version{}}}},
            }},
            {JSFeature::kNodeColonPrefixRequire, {
                {Engine::kES,   {{Version{0, 0, 0}}}},
                {Engine::kNode, {{Version{14, 18, 0}, Version{15, 0, 0}}, {Version{16, 0, 0}, Version{}}}},
            }},
            {JSFeature::kNullishCoalescing, {
                {Engine::kChrome,  {{Version{80, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{80, 0, 0}}}},
                {Engine::kES,      {{Version{2020, 0, 0}}}},
                {Engine::kFirefox, {{Version{72, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{13, 4, 0}}}},
                {Engine::kNode,    {{Version{14, 0, 0}}}},
                {Engine::kOpera,   {{Version{67, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 8, 0}}}},
                {Engine::kSafari,  {{Version{13, 1, 0}}}},
            }},
            {JSFeature::kObjectAccessors, {
                {Engine::kChrome,  {{Version{5, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{12, 0, 0}}}},
                {Engine::kES,      {{Version{5, 0, 0}}}},
                {Engine::kFirefox, {{Version{2, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIE,      {{Version{9, 0, 0}}}},
                {Engine::kIOS,     {{Version{6, 0, 0}}}},
                {Engine::kNode,    {{Version{0, 4, 0}}}},
                {Engine::kOpera,   {{Version{10, 10, 0}}}},
                {Engine::kRhino,   {{Version{1, 7, 13}}}},
                {Engine::kSafari,  {{Version{3, 1, 0}}}},
            }},
            {JSFeature::kObjectExtensions, {
                {Engine::kChrome,  {{Version{44, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{12, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{34, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{4, 0, 0}}}},
                {Engine::kOpera,   {{Version{31, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 8, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kObjectRestSpread, {
                {Engine::kChrome,  {{Version{60, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2018, 0, 0}}}},
                {Engine::kFirefox, {{Version{55, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{11, 3, 0}}}},
                {Engine::kNode,    {{Version{8, 3, 0}}}},
                {Engine::kOpera,   {{Version{47, 0, 0}}}},
                {Engine::kSafari,  {{Version{11, 1, 0}}}},
            }},
            {JSFeature::kOptionalCatchBinding, {
                {Engine::kChrome,  {{Version{66, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2019, 0, 0}}}},
                {Engine::kFirefox, {{Version{58, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 12, 0}}}},
                {Engine::kIOS,     {{Version{11, 3, 0}}}},
                {Engine::kNode,    {{Version{10, 0, 0}}}},
                {Engine::kOpera,   {{Version{53, 0, 0}}}},
                {Engine::kSafari,  {{Version{11, 1, 0}}}},
            }},
            {JSFeature::kOptionalChain, {
                {Engine::kChrome,  {{Version{91, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 9, 0}}}},
                {Engine::kEdge,    {{Version{91, 0, 0}}}},
                {Engine::kES,      {{Version{2020, 0, 0}}}},
                {Engine::kFirefox, {{Version{74, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 12, 0}}}},
                {Engine::kIOS,     {{Version{13, 4, 0}}}},
                {Engine::kNode,    {{Version{16, 9, 0}}}},
                {Engine::kOpera,   {{Version{77, 0, 0}}}},
                {Engine::kSafari,  {{Version{13, 1, 0}}}},
            }},
            {JSFeature::kRegexpDotAllFlag, {
                {Engine::kChrome,  {{Version{62, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2018, 0, 0}}}},
                {Engine::kFirefox, {{Version{78, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{11, 3, 0}}}},
                {Engine::kNode,    {{Version{8, 10, 0}}}},
                {Engine::kOpera,   {{Version{49, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 7, 15}}}},
                {Engine::kSafari,  {{Version{11, 1, 0}}}},
            }},
            {JSFeature::kRegexpLookbehindAssertions, {
                {Engine::kChrome,  {{Version{62, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2018, 0, 0}}}},
                {Engine::kFirefox, {{Version{78, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{16, 4, 0}}}},
                {Engine::kNode,    {{Version{8, 10, 0}}}},
                {Engine::kOpera,   {{Version{49, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 9, 0}}}},
                {Engine::kSafari,  {{Version{16, 4, 0}}}},
            }},
            {JSFeature::kRegexpMatchIndices, {
                {Engine::kChrome,  {{Version{90, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 8, 0}}}},
                {Engine::kEdge,    {{Version{90, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{88, 0, 0}}}},
                {Engine::kIOS,     {{Version{15, 0, 0}}}},
                {Engine::kNode,    {{Version{16, 0, 0}}}},
                {Engine::kOpera,   {{Version{76, 0, 0}}}},
                {Engine::kSafari,  {{Version{15, 0, 0}}}},
            }},
            {JSFeature::kRegexpNamedCaptureGroups, {
                {Engine::kChrome,  {{Version{64, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2018, 0, 0}}}},
                {Engine::kFirefox, {{Version{78, 0, 0}}}},
                {Engine::kIOS,     {{Version{11, 3, 0}}}},
                {Engine::kNode,    {{Version{10, 0, 0}}}},
                {Engine::kOpera,   {{Version{51, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 9, 0}}}},
                {Engine::kSafari,  {{Version{11, 1, 0}}}},
            }},
            {JSFeature::kRegexpSetNotation, {
                {Engine::kES, {{Version{2024, 0, 0}}}},
            }},
            {JSFeature::kRegexpStickyAndUnicodeFlags, {
                {Engine::kChrome,  {{Version{50, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{13, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{46, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{12, 0, 0}}}},
                {Engine::kNode,    {{Version{6, 0, 0}}}},
                {Engine::kOpera,   {{Version{37, 0, 0}}}},
                {Engine::kSafari,  {{Version{12, 0, 0}}}},
            }},
            {JSFeature::kRegexpUnicodePropertyEscapes, {
                {Engine::kES,      {{Version{2018, 0, 0}}}},
                {Engine::kFirefox, {{Version{147, 0, 0}}}},
            }},
            {JSFeature::kRestArgument, {
                {Engine::kChrome,  {{Version{47, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{12, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{43, 0, 0}}}},
                {Engine::kIOS,     {{Version{10, 0, 0}}}},
                {Engine::kNode,    {{Version{6, 0, 0}}}},
                {Engine::kOpera,   {{Version{34, 0, 0}}}},
                {Engine::kSafari,  {{Version{10, 0, 0}}}},
            }},
            {JSFeature::kTemplateLiteral, {
                {Engine::kChrome,  {{Version{62, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{79, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{53, 0, 0}}}},
                {Engine::kIOS,     {{Version{13, 0, 0}}}},
                {Engine::kNode,    {{Version{8, 10, 0}}}},
                {Engine::kOpera,   {{Version{49, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 9, 0}}}},
                {Engine::kSafari,  {{Version{13, 0, 0}}}},
            }},
            {JSFeature::kTopLevelAwait, {
                {Engine::kChrome,  {{Version{89, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{89, 0, 0}}}},
                {Engine::kES,      {{Version{2022, 0, 0}}}},
                {Engine::kFirefox, {{Version{89, 0, 0}}}},
                {Engine::kIOS,     {{Version{15, 0, 0}}}},
                {Engine::kNode,    {{Version{14, 8, 0}}}},
                {Engine::kOpera,   {{Version{75, 0, 0}}}},
                {Engine::kSafari,  {{Version{15, 0, 0}}}},
            }},
            {JSFeature::kTypeofExoticObjectIsObject, {
                {Engine::kChrome,  {{Version{0, 0, 0}}}},
                {Engine::kDeno,    {{Version{0, 0, 0}}}},
                {Engine::kEdge,    {{Version{0, 0, 0}}}},
                {Engine::kES,      {{Version{2020, 0, 0}}}},
                {Engine::kFirefox, {{Version{0, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 0, 0}}}},
                {Engine::kIOS,     {{Version{0, 0, 0}}}},
                {Engine::kNode,    {{Version{0, 0, 0}}}},
                {Engine::kOpera,   {{Version{0, 0, 0}}}},
                {Engine::kRhino,   {{Version{0, 0, 0}}}},
                {Engine::kSafari,  {{Version{0, 0, 0}}}},
            }},
            {JSFeature::kUnicodeEscapes, {
                {Engine::kChrome,  {{Version{44, 0, 0}}}},
                {Engine::kDeno,    {{Version{1, 0, 0}}}},
                {Engine::kEdge,    {{Version{12, 0, 0}}}},
                {Engine::kES,      {{Version{2015, 0, 0}}}},
                {Engine::kFirefox, {{Version{53, 0, 0}}}},
                {Engine::kHermes,  {{Version{0, 7, 0}}}},
                {Engine::kIOS,     {{Version{9, 0, 0}}}},
                {Engine::kNode,    {{Version{4, 0, 0}}}},
                {Engine::kOpera,   {{Version{31, 0, 0}}}},
                {Engine::kRhino,   {{Version{1, 7, 15}}}},
                {Engine::kSafari,  {{Version{9, 0, 0}}}},
            }},
            {JSFeature::kUsing, {
                {Engine::kChrome,  {{Version{141, 0, 0}}}},
                {Engine::kEdge,    {{Version{141, 0, 0}}}},
                {Engine::kFirefox, {{Version{141, 0, 0}}}},
                {Engine::kNode,    {{Version{25, 0, 0}}}},
            }},
        };
    }

    JSFeature UnsupportedJSFeatures(const std::unordered_map<Engine, Semver>& constraints) {
        JSFeature unsupported = static_cast<JSFeature>(0);
        for (const auto& [feature, engines] : kJsTable) {
            if (feature == JSFeature::kInlineScript) {
                continue; // This is purely user-specified
            }
            for (const auto& [engine, version] : constraints) {
                auto it = engines.find(engine);
                if (it == engines.end() || !IsVersionSupported(it->second, version)) {
                    unsupported |= feature;
                }
            }
        }
        return unsupported;
    }
}
