#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>

// CSS property names and their internal identifiers.
//
// Guchho's CSS pipeline works with compact numeric identifiers instead of
// comparing raw property-name strings. Every property Guchho is able to emit
// is enumerated here, which includes standard CSS properties, SVG
// presentation attributes that can appear inside stylesheets (fill, stroke,
// paint-order, ...), legacy aliases kept verbatim for compatibility
// (kDWordWrap, kDCssFloat), the CSS Modules "composes" pseudo-property, and
// a small set of Guchho-internal helper properties (kDCssText).
//
// The lowercase, hyphenated spelling used in real stylesheets
// (e.g. "border-bottom-left-radius") is the canonical form referenced
// throughout the printer and exposed via the declarations lookup map.

namespace guchho::css {
    // Identifies a single CSS property declaration. Each enumerator's value
    // is stable and unique; code must never rely on the numeric ordering of
    // the list (it roughly follows alphabetical order but that is an
    // accident of layout, not a contract).
    //
    // kDUnknown is deliberately the first enumerator so it occupies the
    // value 0 and doubles as the "no property" / "unrecognized" fallback
    // for variables that default-initialize a Declarations value.
    //
    // The kD prefix stands for "known declaration". Values are stored in a
    // 16-bit underlying type, which keeps the identifiers compact enough to
    // embed directly in per-property side tables without bloating them.
    enum Declarations : uint16_t {
        kDUnknown,
        kDAlignContent,
        kDAlignItems,
        kDAlignSelf,
        kDAlignmentBaseline,
        kDAll,
        kDAnimation,
        kDAnimationDelay,
        kDAnimationDirection,
        kDAnimationDuration,
        kDAnimationFillMode,
        kDAnimationIterationCount,
        kDAnimationName,
        kDAnimationPlayState,
        kDAnimationTimingFunction,
        kDAppearance,
        kDBackdropFilter,
        kDBackfaceVisibility,
        kDBackground,
        kDBackgroundAttachment,
        kDBackgroundClip,
        kDBackgroundColor,
        kDBackgroundImage,
        kDBackgroundOrigin,
        kDBackgroundPosition,
        kDBackgroundPositionX,
        kDBackgroundPositionY,
        kDBackgroundRepeat,
        kDBackgroundSize,
        kDBaselineShift,
        kDBlockSize,
        kDBorder,
        kDBorderBlockEnd,
        kDBorderBlockEndColor,
        kDBorderBlockEndStyle,
        kDBorderBlockEndWidth,
        kDBorderBlockStart,
        kDBorderBlockStartColor,
        kDBorderBlockStartStyle,
        kDBorderBlockStartWidth,
        kDBorderBottom,
        kDBorderBottomColor,
        kDBorderBottomLeftRadius,
        kDBorderBottomRightRadius,
        kDBorderBottomStyle,
        kDBorderBottomWidth,
        kDBorderCollapse,
        kDBorderColor,
        kDBorderImage,
        kDBorderImageOutset,
        kDBorderImageRepeat,
        kDBorderImageSlice,
        kDBorderImageSource,
        kDBorderImageWidth,
        kDBorderInlineEnd,
        kDBorderInlineEndColor,
        kDBorderInlineEndStyle,
        kDBorderInlineEndWidth,
        kDBorderInlineStart,
        kDBorderInlineStartColor,
        kDBorderInlineStartStyle,
        kDBorderInlineStartWidth,
        kDBorderLeft,
        kDBorderLeftColor,
        kDBorderLeftStyle,
        kDBorderLeftWidth,
        kDBorderRadius,
        kDBorderRight,
        kDBorderRightColor,
        kDBorderRightStyle,
        kDBorderRightWidth,
        kDBorderSpacing,
        kDBorderStyle,
        kDBorderTop,
        kDBorderTopColor,
        kDBorderTopLeftRadius,
        kDBorderTopRightRadius,
        kDBorderTopStyle,
        kDBorderTopWidth,
        kDBorderWidth,
        kDBottom,
        kDBoxDecorationBreak,
        kDBoxShadow,
        kDBoxSizing,
        kDBreakAfter,
        kDBreakBefore,
        kDBreakInside,
        kDCaptionSide,
        kDCaretColor,
        kDClear,
        kDClip,
        kDClipPath,
        kDClipRule,
        kDColor,
        kDColorInterpolation,
        kDColorInterpolationFilters,
        kDColumnCount,
        kDColumnFill,
        kDColumnGap,
        kDColumnRule,
        kDColumnRuleColor,
        kDColumnRuleStyle,
        kDColumnRuleWidth,
        kDColumnSpan,
        kDColumnWidth,
        kDColumns,
        kDComposes,
        kDContainer,
        kDContainerName,
        kDContainerType,
        kDContent,
        kDCounterIncrement,
        kDCounterReset,
        kDCssFloat,
        kDCssText,
        kDCursor,
        kDDirection,
        kDDisplay,
        kDDominantBaseline,
        kDEmptyCells,
        kDFill,
        kDFillOpacity,
        kDFillRule,
        kDFilter,
        kDFlex,
        kDFlexBasis,
        kDFlexDirection,
        kDFlexFlow,
        kDFlexGrow,
        kDFlexShrink,
        kDFlexWrap,
        kDFloat,
        kDFloodColor,
        kDFloodOpacity,
        kDFont,
        kDFontFamily,
        kDFontFeatureSettings,
        kDFontKerning,
        kDFontSize,
        kDFontSizeAdjust,
        kDFontStretch,
        kDFontStyle,
        kDFontSynthesis,
        kDFontVariant,
        kDFontVariantCaps,
        kDFontVariantEastAsian,
        kDFontVariantLigatures,
        kDFontVariantNumeric,
        kDFontVariantPosition,
        kDFontWeight,
        kDGap,
        kDGlyphOrientationVertical,
        kDGrid,
        kDGridArea,
        kDGridAutoColumns,
        kDGridAutoFlow,
        kDGridAutoRows,
        kDGridColumn,
        kDGridColumnEnd,
        kDGridColumnGap,
        kDGridColumnStart,
        kDGridGap,
        kDGridRow,
        kDGridRowEnd,
        kDGridRowGap,
        kDGridRowStart,
        kDGridTemplate,
        kDGridTemplateAreas,
        kDGridTemplateColumns,
        kDGridTemplateRows,
        kDHeight,
        kDHyphens,
        kDImageOrientation,
        kDImageRendering,
        kDInitialLetter,
        kDInlineSize,
        kDInset,
        kDJustifyContent,
        kDJustifyItems,
        kDJustifySelf,
        kDLeft,
        kDLetterSpacing,
        kDLightingColor,
        kDLineBreak,
        kDLineHeight,
        kDListStyle,
        kDListStyleImage,
        kDListStylePosition,
        kDListStyleType,
        kDMargin,
        kDMarginBlockEnd,
        kDMarginBlockStart,
        kDMarginBottom,
        kDMarginInlineEnd,
        kDMarginInlineStart,
        kDMarginLeft,
        kDMarginRight,
        kDMarginTop,
        kDMarker,
        kDMarkerEnd,
        kDMarkerMid,
        kDMarkerStart,
        kDMask,
        kDMaskComposite,
        kDMaskImage,
        kDMaskOrigin,
        kDMaskPosition,
        kDMaskRepeat,
        kDMaskSize,
        kDMaskType,
        kDMaxBlockSize,
        kDMaxHeight,
        kDMaxInlineSize,
        kDMaxWidth,
        kDMinBlockSize,
        kDMinHeight,
        kDMinInlineSize,
        kDMinWidth,
        kDObjectFit,
        kDObjectPosition,
        kDOpacity,
        kDOrder,
        kDOrphans,
        kDOutline,
        kDOutlineColor,
        kDOutlineOffset,
        kDOutlineStyle,
        kDOutlineWidth,
        kDOverflow,
        kDOverflowAnchor,
        kDOverflowWrap,
        kDOverflowX,
        kDOverflowY,
        kDOverscrollBehavior,
        kDOverscrollBehaviorBlock,
        kDOverscrollBehaviorInline,
        kDOverscrollBehaviorX,
        kDOverscrollBehaviorY,
        kDPadding,
        kDPaddingBlockEnd,
        kDPaddingBlockStart,
        kDPaddingBottom,
        kDPaddingInlineEnd,
        kDPaddingInlineStart,
        kDPaddingLeft,
        kDPaddingRight,
        kDPaddingTop,
        kDPageBreakAfter,
        kDPageBreakBefore,
        kDPageBreakInside,
        kDPaintOrder,
        kDPerspective,
        kDPerspectiveOrigin,
        kDPlaceContent,
        kDPlaceItems,
        kDPlaceSelf,
        kDPointerEvents,
        kDPosition,
        kDPrintColorAdjust,
        kDQuotes,
        kDResize,
        kDRight,
        kDRotate,
        kDRowGap,
        kDRubyAlign,
        kDRubyPosition,
        kDScale,
        kDScrollBehavior,
        kDShapeRendering,
        kDStopColor,
        kDStopOpacity,
        kDStroke,
        kDStrokeDasharray,
        kDStrokeDashoffset,
        kDStrokeLinecap,
        kDStrokeLinejoin,
        kDStrokeMiterlimit,
        kDStrokeOpacity,
        kDStrokeWidth,
        kDTabSize,
        kDTableLayout,
        kDTextAlign,
        kDTextAlignLast,
        kDTextAnchor,
        kDTextCombineUpright,
        kDTextDecoration,
        kDTextDecorationColor,
        kDTextDecorationLine,
        kDTextDecorationSkip,
        kDTextDecorationStyle,
        kDTextEmphasis,
        kDTextEmphasisColor,
        kDTextEmphasisPosition,
        kDTextEmphasisStyle,
        kDTextIndent,
        kDTextJustify,
        kDTextOrientation,
        kDTextOverflow,
        kDTextRendering,
        kDTextShadow,
        kDTextSizeAdjust,
        kDTextTransform,
        kDTextUnderlinePosition,
        kDTop,
        kDTouchAction,
        kDTransform,
        kDTransformBox,
        kDTransformOrigin,
        kDTransformStyle,
        kDTransition,
        kDTransitionDelay,
        kDTransitionDuration,
        kDTransitionProperty,
        kDTransitionTimingFunction,
        kDTranslate,
        kDUnicodeBidi,
        kDUserSelect,
        kDVerticalAlign,
        kDVisibility,
        kDWhiteSpace,
        kDWidows,
        kDWidth,
        kDWillChange,
        kDWordBreak,
        kDWordSpacing,
        kDWordWrap,
        kDWritingMode,
        kDZIndex,
        kDZoom,
    };

    // Maps the exact, lowercase, hyphenated spelling of a property (as it
    // appears in a stylesheet) to its Declarations identifier. Keys are
    // compared byte-for-byte, so lookups are strictly case-sensitive.
    //
    // Example:
    //   KnownDeclarations.at("border-bottom-left-radius") -> kDBorderBottomLeftRadius
    //   KnownDeclarations.at("max-width")                 -> kDMaxWidth
    //   KnownDeclarations.contains("color")               -> true
    //
    // The table is immutable once static initialization completes and is
    // shared read-only across all threads. Besides direct property lookups,
    // it also feeds the set of valid names used by MaybeCorrectDeclarationTypo.
    extern const std::unordered_map<std::string_view, Declarations> KnownDeclarations;

    // Attempts to recover the intended property name when "text" is
    // misspelled by comparing it against every known declaration and
    // returning the closest candidate. A non-null result is always one of
    // the canonical spellings held in KnownDeclarations.
    //
    // Example:
    //   MaybeCorrectDeclarationTypo("boder-radius")   -> optional("border-radius")
    //   MaybeCorrectDeclarationTypo("animation-name") -> nullopt (already correct)
    //   MaybeCorrectDeclarationTypo("--my-scale")     -> nullopt (custom property)
    //
    // Behavior and edge cases:
    //   - Custom properties (any name starting with "--", e.g. "--my-scale")
    //     always yield nullopt: user-defined names must never be rewritten.
    //   - The spelling detector is built lazily on first use and guarded by
    //     a mutex, so the first call is slightly slower but every subsequent
    //     call reuses the precomputed table.
    //   - The call also returns nullopt when the text is already valid or is
    //     too far from any known property; callers can therefore distinguish
    //     "no correction needed" from "nothing to fix".
    std::optional<std::string> MaybeCorrectDeclarationTypo(std::string_view text);
}