#include "guchho/linker.hpp"

#include <algorithm>
#include <cstring>
#include <mutex>
#include <optional>
#include <thread>
#include <unordered_set>

#include "guchho/bundler.hpp"
#include "guchho/javascript/js_runtime.hpp"
#include "guchho/resolver.hpp"

namespace guchho::linker {



    // Wraps a logger so that its error state can be observed from several worker
    // threads at once. Every message is forwarded to the original logger; when an
    // error message arrives a shared flag is raised, and has_errors() reports
    // whether any error has been seen so far. The shared mutex serialises access
    // to that flag so concurrent writers cannot race.
    static logger::Log WrappedLog(logger::Log log) {
        auto mutex = std::make_shared<std::mutex>();
        auto has_errors = std::make_shared<bool>(false);
        auto orig_add_msg = log.add_msg;
        log.add_msg = [mutex, has_errors, orig_add_msg](const logger::Msg& msg) {
            if (msg.kind == logger::MsgKind::kError) {
                std::lock_guard<std::mutex> lock(*mutex);
                *has_errors = true;
            }
            orig_add_msg(msg);
        };
        log.has_errors = [mutex, has_errors]() -> bool {
            std::lock_guard<std::mutex> lock(*mutex);
            return *has_errors;
        };
        return log;
    }



    // Appends a 32-bit value to an Xxh64 hasher in little-endian byte order.
    // Fixing the byte order keeps content hashes identical across platforms and
    // lets several values be concatenated without ambiguity.
    static void HashWriteUint32(helpers::Xxh64& h, uint32_t value) {
        uint8_t buf[4] = {
            static_cast<uint8_t>(value),
            static_cast<uint8_t>(value >> 8),
            static_cast<uint8_t>(value >> 16),
            static_cast<uint8_t>(value >> 24),
        };
        h.Write(buf, 4);
    }



    // Appends a length-prefixed byte string to an Xxh64 hasher: the 32-bit
    // length first, then the bytes themselves. The length prefix disambiguates
    // adjacent values, so hashing "ab"+"c" differs from hashing "a"+"bc".
    static void HashWriteLengthPrefixed(helpers::Xxh64& h, std::string_view bytes) {
        HashWriteUint32(h, static_cast<uint32_t>(bytes.size()));
        h.Write(bytes.data(), bytes.size());
    }



    // Joins a configured public path with a chunk-relative path and normalises
    // the result. Leading "./" and "/" segments on the relative side are
    // stripped, an empty public path becomes ".", and a trailing slash on the
    // public path is never doubled.
    //
    // Input : public_path = "/assets/", rel_path = "./chunk-2.js"
    // Output: "/assets/chunk-2.js"
    static std::string JoinWithPublicPath(const std::string& public_path, const std::string& rel_path) {
        std::string rel = rel_path;
        if (rel.size() >= 2 && rel[0] == '.' && rel[1] == '/') {
            rel = rel.substr(2);
            while (true) {
                if (!rel.empty() && rel[0] == '/') {
                    rel = rel.substr(1);
                } else if (rel.size() >= 2 && rel[0] == '.' && rel[1] == '/') {
                    rel = rel.substr(2);
                } else {
                    break;
                }
            }
        }
        std::string pub = public_path;
        if (pub.empty()) pub = ".";
        std::string slash = "/";
        if (!pub.empty() && pub.back() == '/') slash = "";
        return pub + slash + rel;
    }



    ////////////////////////////////////////////////////////////////////////////////
    // Hashing and source-map helpers
    //
    // The linker names each chunk after a hash of its contents and emits a source
    // map beside it. The helpers below fold everything that influences a chunk's
    // bytes into a stable digest, and serialise the source map that lets a
    // debugger map generated positions back to the original files.
    ////////////////////////////////////////////////////////////////////////////////

    // Folds the content hash of a chunk and every chunk it imports into `hash`.
    //
    // A chunk's "isolated hash" covers its generated bytes plus the output paths
    // of any file-loader assets it references. Walking the import graph means a
    // chunk that merely references a renamed asset still produces a different
    // digest, so cache keys and content-addressed file names stay correct.
    //
    // The walk is depth-first over cross_chunk_imports. Because that graph may
    // contain cycles, each chunk is stamped in `visited` with the caller's
    // `visited_key`; a chunk is folded in at most once per root, yet every chunk
    // caught inside a cycle is still included. A distinct key per root keeps one
    // root's traversal from suppressing another's.
    //
    // Input : chunk A imports B and C, and B imports C; each has an isolated hash.
    // Output: `hash` folds C, then B, then A (with their asset paths) once each.
    void LinkerContext::AppendIsolatedHashesForImportedChunks(helpers::Xxh64& hash, uint32_t chunk_index, std::vector<uint32_t>& visited, uint32_t visited_key) {
        if (visited[chunk_index] == visited_key) return;
        visited[chunk_index] = visited_key;
        auto& chunk = chunks[chunk_index];

        for (auto& imp : chunk.cross_chunk_imports) {
            AppendIsolatedHashesForImportedChunks(hash, imp.chunk_index, visited, visited_key);
        }

        for (auto& piece : chunk.intermediate_output.pieces) {
            if (piece.kind == OutputPieceIndexKind::kAssetIndex) {
                auto& file = graph.files[piece.index];
                if (file.input_file.additional_files.size() != 1) continue;
                auto rel_path = fs->Rel(options->AbsOutputDir, file.input_file.additional_files[0].abs_path);
                if (rel_path.has_value()) {
                    std::replace(rel_path->begin(), rel_path->end(), '\\', '/');
                    HashWriteLengthPrefixed(hash, static_cast<std::string_view>(*rel_path));
                }
            }
        }

        if (chunk.wait_for_isolated_hash) {
            auto h = chunk.wait_for_isolated_hash();
            hash.Write(h.data(), h.size());
        }
    }



    ////////////////////////////////////////////////////////////////////////////////
    // Output assembly
    //
    // While a chunk is generated, its references to other chunks and to copied
    // assets are written as temporary unique-key markers. The routines here split
    // that output into typed pieces, swap the markers for final relative paths
    // once hashes are known, and keep the source map in step with the edits.
    ////////////////////////////////////////////////////////////////////////////////

    // Splits a chunk's assembled output into typed pieces around unique-key
    // markers. Each marker encodes a kind ('A' for an asset, 'C' for a chunk)
    // and an 8-digit decimal index, so a later pass can replace it with the final
    // path of that asset or chunk.
    //
    // When the marker prefix never occurs the original joiner is reused as-is,
    // which avoids copying the whole output.
    //
    // Input : "head" + prefix + "C00000003" + "tail"
    // Output: pieces [text "head", chunk 3, text "tail"]
    IntermediateOutput LinkerContext::BreakJoinerIntoPieces(helpers::Joiner j) {
        if (!j.Contains(unique_key_prefix, std::span<const char>(reinterpret_cast<const char*>(unique_key_prefix_bytes.data()), unique_key_prefix_bytes.size()))) {
            IntermediateOutput out;
            out.joiner = std::move(j);
            return out;
        }
        return BreakOutputIntoPieces(j.Done());
    }



    // The scanning half of BreakJoinerIntoPieces, operating on a flat string.
    // Every unique-key marker is decoded into a kind and an index; a malformed
    // marker, or an index outside the file/chunk tables, is treated as ordinary
    // text so corrupted output can never trigger an out-of-range access.
    //
    // Input : "x" + prefix + "A00000007" + "y"
    // Output: pieces [text "x", asset 7, text "y"]
    IntermediateOutput LinkerContext::BreakOutputIntoPieces(std::string_view output) {
        std::vector<OutputPiece> pieces;
        while (!output.empty()) {
            auto pos = output.find(unique_key_prefix);
            if (pos == std::string_view::npos) {
                pieces.push_back(OutputPiece{
                    .data = std::vector<uint8_t>(output.begin(), output.end()),
                });
                break;
            }
            auto boundary = pos;
            auto start = boundary + unique_key_prefix.size();
            OutputPieceIndexKind kind = OutputPieceIndexKind::kNone;
            uint32_t index = 0;
            if (start + 9 <= output.size()) {
                switch (output[start]) {
                case 'A': kind = OutputPieceIndexKind::kAssetIndex; break;
                case 'C': kind = OutputPieceIndexKind::kChunkIndex; break;
                }
                if (kind != OutputPieceIndexKind::kNone) {
                    bool valid = true;
                    for (size_t j = 1; j < 9; j++) {
                        auto c = output[start + j];
                        if (c < '0' || c > '9') { valid = false; break; }
                        index = index * 10 + static_cast<uint32_t>(c - '0');
                    }
                    if (!valid) { kind = OutputPieceIndexKind::kNone; }
                    if (kind == OutputPieceIndexKind::kAssetIndex && index >= static_cast<uint32_t>(graph.files.size())) {
                        kind = OutputPieceIndexKind::kNone;
                    }
                    if (kind == OutputPieceIndexKind::kChunkIndex && index >= static_cast<uint32_t>(chunks.size())) {
                        kind = OutputPieceIndexKind::kNone;
                    }
                }
            }
            if (kind == OutputPieceIndexKind::kNone) {
                pieces.push_back(OutputPiece{
                    .data = std::vector<uint8_t>(output.begin(), output.end()),
                });
                break;
            }
            pieces.push_back(OutputPiece{
                .data = std::vector<uint8_t>(output.begin(), output.begin() + static_cast<ptrdiff_t>(boundary)),
                .index = index,
                .kind = kind,
            });
            output = output.substr(boundary + unique_key_prefix.size() + 9);
        }
        IntermediateOutput out;
        out.pieces = std::move(pieces);
        return out;
    }



    // Rebuilds a chunk's output with every temporary marker replaced by its
    // final import path, and records the source-map shifts those replacements
    // cause.
    //
    // `modify_path` turns a path relative to the output directory into the text
    // that should actually appear (this is where a configured public path is
    // applied). Each asset/chunk marker is swapped for the new path, and the
    // before/after line-column offsets are advanced so the source map can be
    // corrected afterwards.
    //
    // Input : a marker for asset 7 whose final path is "assets/logo.png"
    // Output: the joiner with "assets/logo.png" in place of the marker, plus one
    //         SourceMapShift describing the length change.
    std::pair<helpers::Joiner, std::vector<sourcemap::SourceMapShift>> LinkerContext::SubstituteFinalPaths(
        const IntermediateOutput& intermediate, std::function<std::string(std::string)> modify_path) {
        if (intermediate.pieces.empty()) {
            return {intermediate.joiner, {{}}};
        }
        helpers::Joiner j;
        std::vector<sourcemap::SourceMapShift> shifts;
        sourcemap::SourceMapShift shift;
        shifts.push_back(shift);
        for (auto& piece : intermediate.pieces) {
            sourcemap::LineColumnOffset data_offset;
            j.AddBytes(std::string_view(reinterpret_cast<const char*>(piece.data.data()), piece.data.size()));
            data_offset.AdvanceBytes(std::string_view(reinterpret_cast<const char*>(piece.data.data()), piece.data.size()));
            shift.before.Add(data_offset);
            shift.after.Add(data_offset);
            if (piece.kind == OutputPieceIndexKind::kAssetIndex) {
                auto& file = graph.files[piece.index];
                if (file.input_file.additional_files.size() != 1) continue;
                auto rel = fs->Rel(options->AbsOutputDir, file.input_file.additional_files[0].abs_path);
                if (rel) {
                    std::replace(rel->begin(), rel->end(), '\\', '/');
                    auto import_path = modify_path(*rel);
                    j.AddString(import_path);
                    shift.before.AdvanceString(file.input_file.unique_key_for_additional_file);
                    shift.after.AdvanceString(import_path);
                    shifts.push_back(shift);
                }
            } else if (piece.kind == OutputPieceIndexKind::kChunkIndex) {
                auto& chunk = chunks[piece.index];
                auto import_path = modify_path(chunk.final_rel_path);
                j.AddString(import_path);
                shift.before.AdvanceString(chunk.unique_key);
                shift.after.AdvanceString(import_path);
                shifts.push_back(shift);
            }
        }
        return {std::move(j), shifts};
    }



    // Computes the import path leading from one chunk's output directory to
    // another output path. A configured public path is prepended verbatim;
    // otherwise a relative path is produced, using forward slashes and a leading
    // "./" or "../" so the result is a valid relative URL. A path that cannot be
    // made relative is reported as a linker error.
    //
    // Input : from_rel_dir = "dist/js", to_rel_path = "dist/css/a.css"
    // Output: "../css/a.css"
    std::string LinkerContext::PathBetweenChunks(const std::string& from_rel_dir, const std::string& to_rel_path) {
        if (!options->PublicPath.empty()) {
            return JoinWithPublicPath(options->PublicPath, to_rel_path);
        }
        auto rel = fs->Rel(from_rel_dir, to_rel_path);
        if (!rel) {
            log.AddError(nullptr, logger::Range{},
                guchho::logger::FormatMsg(guchho::logger::MsgCat::kLinker_CannotTraverseDirectoryToChunk, from_rel_dir, to_rel_path));
            return "";
        }
        std::replace(rel->begin(), rel->end(), '\\', '/');
        if (rel->substr(0, 2) != "./" && rel->substr(0, 3) != "../") {
            *rel = "./" + *rel;
        }
        return *rel;
    }



    // Rejects cycles in the static chunk import graph. A three-colour
    // depth-first search reports the first back edge it finds as a
    // circular-import error. Dynamic imports are skipped because they are
    // allowed to be cyclic.
    void LinkerContext::EnforceNoCyclicChunkImports() {
        std::unordered_map<int, int> colors;
        std::function<bool(int)> validate = [&](int idx) -> bool {
            if (colors[idx] == 1) {
                log.AddError(nullptr, logger::Range{},
                    guchho::logger::FormatMsg(guchho::logger::MsgCat::kLinker_CircularImport));
                return true;
            }
            if (colors[idx] == 2) return false;
            colors[idx] = 1;
            for (auto& imp : chunks[static_cast<size_t>(idx)].cross_chunk_imports) {
                if (imp.import_kind != compiler::ImportKind::kDynamic) {
                    if (validate(static_cast<int>(imp.chunk_index))) return true;
                }
            }
            colors[idx] = 2;
            return false;
        };
        for (size_t i = 0; i < chunks.size(); i++) {
            if (validate(static_cast<int>(i))) break;
        }
    }



    // Serialises the source map for a single chunk as a version-3 JSON object.
    //
    // Input : the per-source compile results (each carrying a generated offset
    //         and the source-map chunk produced while printing), the chunk's
    //         absolute output directory, the pre-quoted source contents, and
    //         whether the map may be split into prefix/mappings/suffix pieces.
    // Output: SourceMapPieces holding "sources", optional "sourceRoot" and
    //         "sourcesContent", the VLQ "mappings" and the original "names".
    //         When shifts are possible the mappings region is returned as its own
    //         piece so path substitutions can be applied to it alone.
    //
    // The ordered sources list is built first (de-duplicated by source index and
    // expanded through any embedded input source map), file: URLs are rewritten
    // relative to the chunk directory, and then the mappings and names are
    // emitted.
    //
    // Example: a chunk built from src/a.js and src/b.js yields
    // "sources":["a.js","b.js"] with their contents and a "mappings" string.
    sourcemap::SourceMapPieces LinkerContext::GenerateSourceMapForChunk(
        const std::vector<CompileResultForSourceMap>& compile_results_for_source_map,
        const std::string& chunk_abs_dir,
        const std::vector<bundler::DataForSourceMap>& data_for_source_maps_list,
        bool can_have_shifts) {

        helpers::Joiner j;
        j.AddString("{\n  \"version\": 3");

        std::unordered_map<uint32_t, int> source_index_to_sources_index;
        struct Item {
            std::string source;
            std::vector<std::string> quoted_contents;
        };
        std::vector<Item> items;
        int next_sources_index = 0;

        for (auto& result : compile_results_for_source_map) {
            if (result.is_null_entry) continue;
            if (source_index_to_sources_index.count(result.source_index)) continue;
            source_index_to_sources_index[result.source_index] = next_sources_index;
            auto& file = graph.files[result.source_index];

            if (!file.input_file.input_source_map) {
                std::vector<std::string> quoted_contents;
                if (!options->ExcludeSourcesContent && result.source_index < data_for_source_maps_list.size()) {
                    if (!data_for_source_maps_list[result.source_index].quoted_contents.empty()) {
                        quoted_contents.push_back(data_for_source_maps_list[result.source_index].quoted_contents[0]);
                    }
                }
                auto source = file.input_file.source.key_path.text;
                if (file.input_file.source.key_path.namespace_ == "file") {
                    source = helpers::FileURLFromFilePath(source);
                } else {
                    if (!file.input_file.source.key_path.namespace_.empty()) {
                        source = file.input_file.source.key_path.namespace_ + ":" + source;
                    }
                    source += file.input_file.source.key_path.ignored_suffix;
                }
                items.push_back({source, std::move(quoted_contents)});
                next_sources_index++;
                continue;
            }

            auto& sm = file.input_file.input_source_map;
            for (size_t i = 0; i < sm->sources.size(); i++) {
                std::vector<std::string> quoted_contents;
                if (!options->ExcludeSourcesContent && result.source_index < data_for_source_maps_list.size()) {
                    if (i < data_for_source_maps_list[result.source_index].quoted_contents.size()) {
                        quoted_contents.push_back(data_for_source_maps_list[result.source_index].quoted_contents[i]);
                    }
                }
                items.push_back({sm->sources[i], std::move(quoted_contents)});
            }
            next_sources_index += static_cast<int>(sm->sources.size());
        }

        j.AddString(",\n  \"sources\": [");
        for (size_t i = 0; i < items.size(); i++) {
            if (i != 0) j.AddString(", ");

            std::string item_source = items[i].source;
            if (!item_source.empty()) {
                size_t scheme_end = item_source.find(':');
                if (scheme_end != std::string::npos) {
                    std::string scheme = item_source.substr(0, scheme_end);
                    size_t p = scheme_end + 1;
                    std::string host;
                    std::string path;
                    if (item_source.size() >= p + 2 && item_source.compare(p, 2, "//") == 0) {
                        p += 2;
                        size_t path_start = item_source.find_first_of("/?#", p);
                        if (path_start == std::string::npos) {
                            size_t end = item_source.find('?', p);
                            end = (end == std::string::npos) ? item_source.size() : end;
                            host = item_source.substr(p, end - p);
                        } else {
                            host = item_source.substr(p, path_start - p);
                            size_t path_end = item_source.find_first_of("?#", path_start);
                            path_end = (path_end == std::string::npos) ? item_source.size() : path_end;
                            path = item_source.substr(path_start, path_end - path_start);
                        }
                    } else {
                        size_t path_end = item_source.find_first_of("?#", p);
                        path_end = (path_end == std::string::npos) ? item_source.size() : path_end;
                        path = item_source.substr(p, path_end - p);
                    }

                    if (helpers::IsFileURL(scheme, host, path)) {
                        std::string source_path = helpers::FilePathFromFileURL(path, chunk_abs_dir);
                        if (auto rel_path = fs->Rel(chunk_abs_dir, source_path); rel_path) {
                            std::string relative = *rel_path;
                            for (auto& ch : relative) {
                                if (ch == '\\') ch = '/';
                            }
                            std::string encoded;
                            encoded.reserve(relative.size());
                            for (char ch : relative) {
                                if (ch == ' ' || ch == '#' || ch == '?' || ch == '%') {
                                    char buf[4];
                                    snprintf(buf, sizeof(buf), "%%%02X", static_cast<unsigned char>(ch));
                                    encoded += buf;
                                } else {
                                    encoded += ch;
                                }
                            }
                            for (size_t pos = 0; (pos = encoded.find("%20", pos)) != std::string::npos; pos += 1) {
                                encoded.replace(pos, 3, " ");
                            }
                            item_source = encoded;
                        }
                    }
                }
            }
            j.AddString(helpers::QuoteForJSON(item_source, options->ASCIIOnly));
        }
        j.AddString("]");

        if (!options->SourceRoot.empty()) {
            j.AddString(",\n  \"sourceRoot\": ");
            j.AddString(helpers::QuoteForJSON(options->SourceRoot, options->ASCIIOnly));
        }

        if (!options->ExcludeSourcesContent) {
            j.AddString(",\n  \"sourcesContent\": [");
            for (size_t i = 0; i < items.size(); i++) {
                if (i != 0) j.AddString(", ");
                for (auto& qc : items[i].quoted_contents) {
                    j.AddString(qc);
                }
            }
            j.AddString("]");
        }

        j.AddString(",\n  \"mappings\": \"");
        auto mappings_start = j.Length();
        sourcemap::SourceMapState prev_end_state;
        int prev_column_offset = 0;

        for (auto& result : compile_results_for_source_map) {
            auto chunk = result.source_map_chunk;
            auto offset = result.generated_offset;
            int sources_index = 0;
            auto it = source_index_to_sources_index.find(result.source_index);
            if (it != source_index_to_sources_index.end()) {
                sources_index = it->second;
            } else {
                if (!result.is_null_entry) continue;
            }

            sourcemap::SourceMapState start_state;
            start_state.source_index = sources_index;
            start_state.generated_line = offset.lines;
            start_state.generated_column = offset.columns;
            if (offset.lines == 0) {
                start_state.generated_column += prev_column_offset;
            }

            if (result.is_null_entry) {
                chunk.buffer.data = "A";
                sourcemap::AppendSourceMapChunk(j, prev_end_state, start_state, chunk.buffer);
                prev_end_state.generated_line = start_state.generated_line;
                prev_end_state.generated_column = start_state.generated_column;
            } else {
                sourcemap::AppendSourceMapChunk(j, prev_end_state, start_state, chunk.buffer);
                auto prev_original_name = prev_end_state.original_name;
                prev_end_state = chunk.end_state;
                prev_end_state.source_index += sources_index;
                if (chunk.buffer.first_name_offset.IsValid()) {
                    prev_end_state.original_name = static_cast<int>(chunk.quoted_names.size());
                } else {
                    prev_end_state.original_name = prev_original_name;
                }
                prev_column_offset = chunk.final_generated_column;
            }

            if (prev_end_state.generated_line == 0) {
                prev_end_state.generated_column += start_state.generated_column;
                prev_column_offset += start_state.generated_column;
            }
        }
        auto mappings_end = j.Length();

        bool is_first_name = true;
        j.AddString("\",\n  \"names\": [");
        for (auto& result : compile_results_for_source_map) {
            for (auto& quoted_name : result.source_map_chunk.quoted_names) {
                if (is_first_name) is_first_name = false;
                else j.AddString(", ");
                j.AddString(quoted_name);
            }
        }
        j.AddString("]");

        j.AddString("\n}\n");
        auto bytes = j.Done();

        sourcemap::SourceMapPieces pieces;
        if (!can_have_shifts) {
            pieces.prefix = std::move(bytes);
        } else {
            pieces.prefix = bytes.substr(0, mappings_start);
            pieces.mappings = bytes.substr(mappings_start, mappings_end - mappings_start);
            pieces.suffix = bytes.substr(mappings_end);
        }
        return pieces;
    }



    // Extension hook for per-file extra data injected during JavaScript code
    // generation. It contributes nothing today and always returns an empty
    // string, but is kept so callers have a stable place to add data later.
    std::string LinkerContext::GenerateExtraDataForFileJS(uint32_t /*source_index*/) {
        return "";
    }



    // Recomputes the exact final byte length of a chunk's output. Plain text
    // pieces contribute their own size, while every asset/chunk marker
    // contributes the length of the path that will replace it. This is used
    // where an exact size is needed before the output has been materialised, for
    // example the "bytes" field of a metafile entry.
    //
    // Input : pieces [text "abc", asset marker whose path is "../img/x.png"]
    // Output: 3 + 13 = 16
    int LinkerContext::AccurateFinalByteCount(const IntermediateOutput& output, const std::string& chunk_final_rel_dir) {
        int count = 0;

        for (auto& piece : output.pieces) {
            count += static_cast<int>(piece.data.size());

            switch (piece.kind) {
            case OutputPieceIndexKind::kAssetIndex: {
                auto& file = graph.files[piece.index];
                if (file.input_file.additional_files.size() != 1) {
                    throw std::runtime_error("Internal error: expected exactly one additional file");
                }
                auto rel = fs->Rel(options->AbsOutputDir, file.input_file.additional_files[0].abs_path);
                if (rel) {
                    std::replace(rel->begin(), rel->end(), '\\', '/');
                    count += static_cast<int>(PathBetweenChunks(chunk_final_rel_dir, *rel).size());
                }
                break;
            }
            case OutputPieceIndexKind::kChunkIndex: {
                auto& chunk = chunks[piece.index];
                count += static_cast<int>(PathBetweenChunks(chunk_final_rel_dir, chunk.final_rel_path).size());
                break;
            }
            default:
                break;
            }
        }

        return count;
    }



    // Appends legal comments to a chunk according to the configured
    // LegalComments mode.
    //
    // Comments are split by origin: comments from files beneath a node_modules
    // directory are grouped by package path and merged when their bodies match,
    // while every other comment is de-duplicated into one first-party list.
    //
    // In kEndOfFile mode the text is written inline at the end of the chunk. In
    // kLinkedWithComment and kExternalWithoutComment modes it is collected into
    // chunk.external_legal_comments for a separate ".LEGAL.txt" file. kNone and
    // kInline do nothing here.
    void LinkerContext::MaybeAppendLegalComments(
        config::LegalComments legal_comments,
        const std::vector<LegalCommentEntry>& legal_comment_list,
        ChunkInfo& chunk,
        helpers::Joiner& j,
        std::string_view slash_tag) {
        switch (legal_comments) {
        case config::LegalComments::kNone:
        case config::LegalComments::kInline:
            return;
        default:
            break;
        }

        struct ThirdPartyEntry {
            std::vector<std::string> package_paths;
            std::vector<std::string> comments;
        };

        std::vector<std::string> unique_first_party_comments;
        std::vector<ThirdPartyEntry> third_party_comments;
        std::unordered_set<std::string> has_first_party_comment;

        for (auto& entry : legal_comment_list) {
            auto& source = graph.files[entry.source_index].input_file.source;
            std::string package_path;

            if (source.key_path.namespace_ != "dataurl") {
                auto path = source.key_path.text;
                int previous = static_cast<int>(path.size());
                while (previous > 0) {
                    auto slash = path.find_last_of("/\\", static_cast<size_t>(previous - 1));
                    auto component = path.substr(slash + 1, static_cast<size_t>(previous) - slash - 1);
                    if (component == "node_modules") {
                        if (previous < static_cast<int>(path.size())) {
                            package_path = path.substr(static_cast<size_t>(previous) + 1);
                            std::replace(package_path.begin(), package_path.end(), '\\', '/');
                        }
                        break;
                    }
                    previous = static_cast<int>(slash);
                }
            }

            if (!package_path.empty()) {
                third_party_comments.push_back({{package_path}, entry.extracted_comments});
            } else {
                for (auto& comment : entry.extracted_comments) {
                    if (!has_first_party_comment.count(comment)) {
                        has_first_party_comment.insert(comment);
                        unique_first_party_comments.push_back(comment);
                    }
                }
            }
        }

        std::unordered_map<std::string, size_t> identical;
        size_t end = 0;
        for (auto& entry : third_party_comments) {
            std::string key;
            for (auto& c : entry.comments) { key += c; key += '\0'; }
            auto it = identical.find(key);
            if (it != identical.end()) {
                for (auto& p : entry.package_paths) {
                    third_party_comments[it->second].package_paths.push_back(p);
                }
            } else {
                identical[key] = end;
                third_party_comments[end] = std::move(entry);
                end++;
            }
        }
        third_party_comments.resize(end);

        switch (legal_comments) {
        case config::LegalComments::kEndOfFile:
            for (auto& comment : unique_first_party_comments) {
                j.AddString(helpers::EscapeClosingTag(comment, slash_tag));
                j.AddString("\n");
            }
            if (!third_party_comments.empty()) {
                j.AddString("/*! Bundled license information:\n");
                for (auto& entry : third_party_comments) {
                    j.AddString("\n");
                    for (auto& pp : entry.package_paths) {
                        j.AddString(helpers::EscapeClosingTag(pp, slash_tag) + ":\n");
                    }
                    for (auto& comment : entry.comments) {
                        auto escaped = helpers::EscapeClosingTag(comment, slash_tag);
                        if (escaped.substr(0, 2) == "//") {
                            j.AddString("  (*" + escaped.substr(2) + " *)\n");
                        } else if (escaped.substr(0, 2) == "/*" && escaped.size() >= 4 && escaped.substr(escaped.size() - 2) == "*/") {
                            auto inner = escaped.substr(1, escaped.size() - 2);
                            std::string formatted = "  (";
                            for (size_t i = 0; i < inner.size(); i++) {
                                char c = inner[i];
                                if (c == '\n') formatted += "\n  ";
                                else formatted += c;
                            }
                            formatted += ")\n";
                            j.AddString(formatted);
                        }
                    }
                }
                j.AddString("*/\n");
            }
            break;

        case config::LegalComments::kLinkedWithComment:
        case config::LegalComments::kExternalWithoutComment: {
            helpers::Joiner j_comments;
            for (auto& comment : unique_first_party_comments) {
                j_comments.AddString(comment);
                j_comments.AddString("\n");
            }
            if (!third_party_comments.empty()) {
                if (!unique_first_party_comments.empty()) {
                    j_comments.AddString("\n");
                }
                j_comments.AddString("Bundled license information:\n");
                for (auto& entry : third_party_comments) {
                    j_comments.AddString("\n");
                    for (auto& pp : entry.package_paths) {
                        j_comments.AddString(pp + ":\n");
                    }
                    for (auto& comment : entry.comments) {
                        std::string indented;
                        for (char c : comment) {
                            if (c == '\n') indented += "\n  ";
                            else indented += c;
                        }
                        j_comments.AddString("  " + indented + "\n");
                    }
                }
            }
            std::string legal_comments_text = j_comments.Done();
            chunk.external_legal_comments = std::vector<uint8_t>(
                legal_comments_text.begin(), legal_comments_text.end());
            break;
        }
        default:
            break;
        }
    }



    ////////////////////////////////////////////////////////////////////////////////
    // Panic recovery
    //
    // Generation runs on worker threads. These helpers turn a failure raised on a
    // worker into a logged linker error that the main thread can surface, so a
    // single bad file does not abort the whole build.
    ////////////////////////////////////////////////////////////////////////////////

    // Translates the in-flight exception into a logged linker error. The
    // exception's message is formatted, and when a concrete source file is
    // involved its path is appended. Non-std::exception throws are reported as
    // an unknown-exception error. Must be called from inside a catch block.
    void LinkerContext::RecoverInternalError(uint32_t source_index) {
        try {
            throw;
        } catch (const std::exception& e) {
            std::string text = logger::FormatMsg(logger::MsgCat::kLinker_PanicPrinting, std::string(e.what()));
            if (source_index != javascript::kSourceIndex) {
                text += logger::FormatMsg(logger::MsgCat::kLinker_PanicWhilePrinting,
                    graph.files[source_index].input_file.source.pretty_paths.Select(options->LogPathStyle));
            }
            log.AddErrorWithNotes(nullptr, {}, text, {});
        } catch (...) {
            std::string text = logger::FormatMsg(logger::MsgCat::kLinker_UnknownExceptionPrinting);
            if (source_index != javascript::kSourceIndex) {
                text += logger::FormatMsg(logger::MsgCat::kLinker_PanicWhilePrinting,
                    graph.files[source_index].input_file.source.pretty_paths.Select(options->LogPathStyle));
            }
            log.AddErrorWithNotes(nullptr, {}, text, {});
        }
    }



    // Prepares the deferred computation of a chunk's "isolated hash".
    //
    // Everything the digest needs is captured by value, because the returned
    // callable outlives this function and runs on a worker thread: the ordered
    // JavaScript part ranges with their namespace and file paths, the final path
    // template, the public path, the assembled output pieces (or the raw joiner
    // bytes), and the source-map prefix/mappings/suffix.
    //
    // The callable mixes all of that into an Xxh64 digest and yields the 8-byte
    // little-endian result. Because both the generated code and its source map
    // feed the hash, changing either one changes the chunk's content hash and
    // therefore its final file name.
    void LinkerContext::GenerateIsolatedHashInParallel(ChunkInfo& chunk) {
        auto public_path = options->PublicPath;
        std::vector<std::tuple<uint32_t, uint32_t, uint32_t, std::string, std::string>> js_parts;
        if (auto* chunk_repr = std::get_if<ChunkReprJS>(&chunk.chunk_repr)) {
            for (auto& part_range : chunk_repr->parts_in_chunk_in_order) {
                auto& file = graph.files[part_range.source_index];
                std::string ns = file.input_file.source.key_path.namespace_;
                std::string file_path;
                if (ns == "file") {
                    file_path = file.input_file.source.pretty_paths.rel;
                } else {
                    file_path = file.input_file.source.key_path.text;
                }
                js_parts.emplace_back(part_range.part_index_begin, part_range.part_index_end, part_range.source_index, std::move(ns), std::move(file_path));
            }
        }
        auto final_template = chunk.final_template;
        auto has_pieces = !chunk.intermediate_output.pieces.empty();
        std::vector<std::vector<uint8_t>> piece_data;
        std::string joiner_bytes;
        if (has_pieces) {
            for (auto& piece : chunk.intermediate_output.pieces) {
                piece_data.push_back(piece.data);
            }
        } else {
            joiner_bytes = chunk.intermediate_output.joiner.Done();
        }
        std::string sm_prefix = chunk.output_source_map.prefix;
        std::string sm_mappings = chunk.output_source_map.mappings;
        std::string sm_suffix = chunk.output_source_map.suffix;

        chunk.wait_for_isolated_hash = [js_parts = std::move(js_parts), final_template = std::move(final_template),
                                         public_path = std::move(public_path), piece_data = std::move(piece_data),
                                         joiner_bytes = std::move(joiner_bytes), has_pieces,
                                         sm_prefix = std::move(sm_prefix), sm_mappings = std::move(sm_mappings), sm_suffix = std::move(sm_suffix)]() -> std::vector<uint8_t> {
            helpers::Xxh64 hash;
            for (auto& [begin, end, source_index, ns, file_path] : js_parts) {
                HashWriteLengthPrefixed(hash, ns);
                HashWriteLengthPrefixed(hash, file_path);
                HashWriteUint32(hash, begin);
                HashWriteUint32(hash, end);
            }
            for (auto& part : final_template) {
                HashWriteLengthPrefixed(hash, part.Data);
            }
            if (!public_path.empty()) {
                HashWriteLengthPrefixed(hash, public_path);
            }
            if (has_pieces) {
                for (auto& data : piece_data) {
                    HashWriteLengthPrefixed(hash, std::string_view(reinterpret_cast<const char*>(data.data()), data.size()));
                }
            } else {
                HashWriteLengthPrefixed(hash, joiner_bytes);
            }
            HashWriteLengthPrefixed(hash, sm_prefix);
            HashWriteLengthPrefixed(hash, sm_mappings);
            HashWriteLengthPrefixed(hash, sm_suffix);
            auto hash_result = hash.Sum64();
            std::vector<uint8_t> result(sizeof(uint64_t));
            for (size_t i = 0; i < 8; i++) {
                result[i] = static_cast<uint8_t>((hash_result >> (i * 8)) & 0xFF);
            }
            return result;
        };
    }



    // Generates every chunk and materialises the final output files.
    //
    // Phase 1 starts one worker per chunk, dispatching JavaScript chunks to
    // GenerateChunkJS and CSS chunks to GenerateChunkCSS, and waits for them all.
    // Cyclic chunk imports are rejected before the workers are joined. Any
    // exception raised on a worker is captured and rethrown on the calling
    // thread, so a failure surfaces as an ordinary catchable error instead of
    // aborting the process.
    //
    // Phase 2 gives each chunk its final relative path by folding the hashes of
    // the chunks it imports into a content hash and substituting that hash into
    // the path template.
    //
    // Phase 3, again in parallel, replaces each chunk's temporary markers with
    // final paths, writes the optional legal-comment and source-map files,
    // builds the metafile JSON metadata, and gathers the copied files.
    //
    // Input : additional output files collected from the entry points.
    // Output: a LinkResult whose output_files are those additional files followed
    //         by each chunk's generated files in chunk order.
    //
    // Example: two entry chunks yield "dist/a.js", "dist/a.js.map", "dist/b.js"
    // and "dist/b.js.map" when linked with external source maps.
    LinkResult LinkerContext::GenerateChunksInParallel(std::vector<graph::OutputFile> additional_files) {
        timer->Begin("Generate chunks");
        std::vector<std::thread> generate_threads;
        std::vector<std::exception_ptr> generate_exceptions(chunks.size());
        generate_threads.reserve(chunks.size());
        for (size_t chunk_index = 0; chunk_index < chunks.size(); chunk_index++) {
            if (std::holds_alternative<ChunkReprJS>(chunks[chunk_index].chunk_repr)) {
                generate_threads.emplace_back([this, chunk_index, &generate_exceptions]() {
                    try {
                        this->GenerateChunkJS(static_cast<int>(chunk_index));
                    } catch (...) {
                        generate_exceptions[chunk_index] = std::current_exception();
                    }
                });
            } else if (std::holds_alternative<ChunkReprCSS>(chunks[chunk_index].chunk_repr)) {
                generate_threads.emplace_back([this, chunk_index, &generate_exceptions]() {
                    try {
                        this->GenerateChunkCSS(static_cast<int>(chunk_index));
                    } catch (...) {
                        generate_exceptions[chunk_index] = std::current_exception();
                    }
                });
            }
        }
        EnforceNoCyclicChunkImports();
        for (auto& t : generate_threads) t.join();
        for (auto& e : generate_exceptions) {
            if (e) std::rethrow_exception(e);
        }
        timer->End("Generate chunks");

        std::vector<uint32_t> visited(chunks.size(), 0);
        for (size_t chunk_index = 0; chunk_index < chunks.size(); chunk_index++) {
            auto& chunk = chunks[chunk_index];
            std::optional<std::string> hash_substitution;
            if (config::HasPlaceholder(chunk.final_template, config::PathPlaceholder::kHash)) {
                helpers::Xxh64 hash;
                AppendIsolatedHashesForImportedChunks(hash, static_cast<uint32_t>(chunk_index), visited, ~static_cast<uint32_t>(chunk_index));
                uint8_t hash_buf[8];
                auto sum = hash.Sum64();
                std::memcpy(hash_buf, &sum, 8);
                auto final_string = bundler::HashForFileName(std::span<const uint8_t>(hash_buf, 8));
                hash_substitution = final_string;
                if (chunk.final_template.size() == 2) {
                    bool is_css = false, is_js = false;
                    for (auto& p : chunk.final_template) {
                        if (p.Data.find("css") != std::string::npos) is_css = true;
                        if (p.Data.find("js") != std::string::npos) is_js = true;
                    }
                    if (is_css || is_js) {
                        std::string ib;
                        if (!chunk.intermediate_output.pieces.empty()) {
                            for (auto& pc : chunk.intermediate_output.pieces) ib += std::string(pc.data.begin(), pc.data.end());
                        } else {
                            ib = chunk.intermediate_output.joiner.Done();
                        }
                        std::string esc;
                        for (size_t i = 0; i < std::min<size_t>(ib.size(), 100); ++i) {
                            char c = ib[i];
                            if (c == '\n') esc += "\\n";
                            else esc += c;
                        }
                    }
                }
            }
            chunk.final_rel_path = config::TemplateToString(
                config::SubstituteTemplate(chunk.final_template, config::PathPlaceholders{.Hash = hash_substitution ? &*hash_substitution : nullptr}));
        }

        timer->Begin("Generate final output files");
        std::vector<std::vector<graph::OutputFile>> results(chunks.size());
        std::vector<std::thread> result_threads;
        std::vector<std::exception_ptr> result_exceptions(chunks.size());
        result_threads.reserve(chunks.size());
        for (size_t chunk_index = 0; chunk_index < chunks.size(); chunk_index++) {
            result_threads.emplace_back([this, &results, &result_exceptions, chunk_index]() {
                try {
                auto& chunk = chunks[chunk_index];
                std::vector<graph::OutputFile> output_files;

                std::string comment_prefix;
                std::string comment_suffix;
                if (auto* chunk_repr = std::get_if<ChunkReprJS>(&chunk.chunk_repr)) {
                    for (auto source_index : chunk_repr->files_in_chunk_in_order) {
                        auto& f = graph.files[source_index].input_file;
                        output_files.insert(output_files.end(), f.additional_files.begin(), f.additional_files.end());
                    }
                    comment_prefix = "//";
                } else if (auto* chunk_repr_css = std::get_if<ChunkReprCSS>(&chunk.chunk_repr)) {
                    for (auto& entry : chunk_repr_css->imports_in_chunk_in_order) {
                        if (entry.kind == CssImportKind::kSourceIndex) {
                            auto& f = graph.files[entry.source_index].input_file;
                            output_files.insert(output_files.end(), f.additional_files.begin(), f.additional_files.end());
                        }
                    }
                    comment_prefix = "/*";
                    comment_suffix = " */";
                }

                auto final_rel_dir = fs->Dir(chunk.final_rel_path);
                auto [output_contents_joiner, output_source_map_shifts] = SubstituteFinalPaths(chunk.intermediate_output,
                    [this, &final_rel_dir](std::string final_rel_path_for_import) {
                        return PathBetweenChunks(final_rel_dir, final_rel_path_for_import);
                    });

                if (!chunk.external_legal_comments.empty()) {
                    std::string final_rel_path_for_legal_comments = chunk.final_rel_path + ".LEGAL.txt";
                    if (options->LegalCommentsData == config::LegalComments::kLinkedWithComment) {
                        std::string import_path = PathBetweenChunks(final_rel_dir, final_rel_path_for_legal_comments);
                        if (import_path.rfind("./", 0) == 0) import_path = import_path.substr(2);
                        output_contents_joiner.EnsureNewlineAtEnd();
                        output_contents_joiner.AddString("/*! For license information please see " + import_path + " */\n");
                    }
                    std::string metafile_json = config::MaybeRemoveWhitespace(options->MetafileFormatData,
                        "{\n      \"imports\": [],\n      \"exports\": [],\n      \"inputs\": {},\n      \"bytes\": " + std::to_string(chunk.external_legal_comments.size()) + "\n    }");
                    output_files.push_back(graph::OutputFile{
                        .json_metadata_chunk = metafile_json,
                        .abs_path = fs->Join({options->AbsOutputDir, final_rel_path_for_legal_comments}),
                        .contents = chunk.external_legal_comments,
                    });
                }

                if (options->SourceMapData != config::SourceMap::kNone && chunk.output_source_map.HasContent()) {
                    auto output_source_map = chunk.output_source_map.Finalize(output_source_map_shifts);
                    std::string final_rel_path_for_source_map = chunk.final_rel_path + ".map";
                    switch (options->SourceMapData) {
                    case config::SourceMap::kLinkedWithComment: {
                        std::string import_path = PathBetweenChunks(final_rel_dir, final_rel_path_for_source_map);
                        if (import_path.rfind("./", 0) == 0) import_path = import_path.substr(2);
                        std::string escaped;
                        for (char c : import_path) {
                            if (c == ' ' || c == '#' || c == '?' || c == '%') {
                                char buf[4];
                                snprintf(buf, sizeof(buf), "%%%02X", static_cast<unsigned char>(c));
                                escaped += buf;
                            } else {
                                escaped += c;
                            }
                        }
                        output_contents_joiner.EnsureNewlineAtEnd();
                        output_contents_joiner.AddString(comment_prefix + "# sourceMappingURL=" + escaped + comment_suffix + "\n");
                        break;
                    }
                    case config::SourceMap::kInline:
                    case config::SourceMap::kInlineAndExternal: {
                        output_contents_joiner.EnsureNewlineAtEnd();
                        output_contents_joiner.AddString(comment_prefix + "# sourceMappingURL=data:application/json;base64,");
                        output_contents_joiner.AddString(helpers::Base64StdEncode(output_source_map));
                        output_contents_joiner.AddString(comment_suffix + "\n");
                        break;
                    }
                    default: break;
                    }
                    switch (options->SourceMapData) {
                    case config::SourceMap::kLinkedWithComment:
                    case config::SourceMap::kInlineAndExternal:
                    case config::SourceMap::kExternalWithoutComment: {
                        std::string metafile_json = config::MaybeRemoveWhitespace(options->MetafileFormatData,
                            "{\n      \"imports\": [],\n      \"exports\": [],\n      \"inputs\": {},\n      \"bytes\": " + std::to_string(output_source_map.size()) + "\n    }");
                        output_files.push_back(graph::OutputFile{
                            .json_metadata_chunk = metafile_json,
                            .abs_path = fs->Join({options->AbsOutputDir, final_rel_path_for_source_map}),
                            .contents = std::vector<uint8_t>(output_source_map.begin(), output_source_map.end()),
                        });
                        break;
                    }
                    default: break;
                    }
                }

                std::string output_contents = output_contents_joiner.Done();

                std::string json_metadata_chunk;
                if (options->NeedsMetafile && chunk.json_metadata_chunk_callback) {
                    auto joiner = chunk.json_metadata_chunk_callback(static_cast<int>(output_contents.size()));
                    auto pieces = BreakJoinerIntoPieces(std::move(joiner));
                    auto modify = [this](std::string final_rel_path_for_import) {
                        auto abs = fs->Join({options->AbsOutputDir, final_rel_path_for_import});
                        logger::Path p{abs, "file"};
                        auto pretty = resolver::MakePrettyPaths(*fs, p);
                        return pretty.Select(options->MetafilePathStyle);
                    };
                    auto [bytes_joiner, _] = SubstituteFinalPaths(pieces, modify);
                    json_metadata_chunk = bytes_joiner.Done();
                }

                output_files.push_back(graph::OutputFile{
                    .json_metadata_chunk = std::move(json_metadata_chunk),
                    .abs_path = fs->Join({options->AbsOutputDir, chunk.final_rel_path}),
                    .contents = std::vector<uint8_t>(output_contents.begin(), output_contents.end()),
                    .is_executable = chunk.is_executable,
                });

                results[chunk_index] = std::move(output_files);
                } catch (...) {
                    result_exceptions[chunk_index] = std::current_exception();
                }
            });
        }
        for (auto& t : result_threads) t.join();
        for (auto& e : result_exceptions) {
            if (e) std::rethrow_exception(e);
        }
        timer->End("Generate final output files");

        std::vector<graph::OutputFile> output_files;
        output_files.reserve(additional_files.size());
        for (auto& r : results) output_files.reserve(output_files.size() + r.size());
        output_files.insert(output_files.end(), additional_files.begin(), additional_files.end());
        for (auto& r : results) {
            output_files.insert(output_files.end(), r.begin(), r.end());
        }
        LinkResult link_result;
        link_result.output_files = std::move(output_files);
        return link_result;
    }



    ////////////////////////////////////////////////////////////////////////////////
    // Main entry point
    //
    // Link() ties the whole pipeline together: clone the graph, scan, tree-shake
    // and code-split, compute chunks, mangle, then generate and assemble output.
    ////////////////////////////////////////////////////////////////////////////////

    // The linker's main entry point: turns the scanned, tree-shaken module graph
    // into final output files.
    //
    // The pipeline runs in order:
    //   1. Wrap the logger so error state is visible across worker threads.
    //   2. Clone the linker graph and configure the LinkerContext (options,
    //      timer, logger, filesystem, resolver, source-map provider and the
    //      unique-key prefix used for temporary output markers).
    //   3. Select the runtime helper symbols (profiler or minified names) and
    //      adjust entry-point export handling for the requested output format.
    //   4. Create the unbound `module`/`exports` symbols that CommonJS, UMD and
    //      System formats need.
    //   5. Scan imports and exports, then tree-shake and code-split. If scanning
    //      reported errors the mangle cache is refreshed and an empty result is
    //      returned.
    //   6. Compute chunks and cross-chunk dependencies, run property and CSS
    //      local-name mangling under the mangle-cache lock, and resolve symbols
    //      so parallel generation cannot race.
    //   7. Generate chunks in parallel, then fill in per-chunk metadata now that
    //      final paths and cross-chunk dependencies are known.
    //
    // Input : input files, entry points, reachable files, a callback yielding
    //         per-source source-map data, and the sources needing a separate CSS
    //         entry.
    // Output: a LinkResult holding the output files and per-chunk metadata.
    //
    // Example: linking a single "src/index.js" entry with minification enabled
    // yields "dist/index.js" plus one ChunkMetadata describing it.
    LinkResult Link(
        config::Options* options,
        helpers::Timer& timer,
        logger::Log& log,
        filesystem::Fs& fs,
        resolver::Resolver& res,
        const std::vector<graph::InputFile>& input_files,
        const std::vector<graph::EntryPoint>& entry_points,
        const std::string& unique_key_prefix,
        const std::vector<uint32_t>& reachable_files,
        std::function<std::vector<bundler::DataForSourceMap>()> data_for_source_maps,
        const std::unordered_set<uint32_t>& separate_css_entry_sources) {

        timer.Begin("Link");
        struct TimerGuard {
            helpers::Timer* t;
            bool done = false;
            ~TimerGuard() { if (!done) t->End("Link"); }
        } link_guard{&timer};

        log = WrappedLog(log);

        timer.Begin("Clone linker graph");
        LinkerContext c;
        c.options = options;
        c.timer = &timer;
        c.log = log;
        c.fs = &fs;
        c.res = &res;
        c.data_for_source_maps = std::move(data_for_source_maps);
        c.unique_key_prefix = unique_key_prefix;
        c.unique_key_prefix_bytes.assign(unique_key_prefix.begin(), unique_key_prefix.end());
        c.graph = graph::CloneLinkerGraph(input_files, reachable_files, entry_points, options->CodeSplitting);
        c.separate_css_entry_sources = separate_css_entry_sources;
        timer.End("Clone linker graph");

        auto& runtime_repr = *std::get<std::shared_ptr<graph::JSRepr>>(c.graph.files[javascript::kSourceIndex].input_file.repr);
        if (options->ProfilerNames) {
            c.cjs_runtime_ref = runtime_repr.ast.named_exports["__commonJS"].ref;
            c.esm_runtime_ref = runtime_repr.ast.named_exports["__esm"].ref;
        } else {
            c.cjs_runtime_ref = runtime_repr.ast.named_exports["__commonJSMin"].ref;
            c.esm_runtime_ref = runtime_repr.ast.named_exports["__esmMin"].ref;
        }

        std::vector<graph::OutputFile> additional_files;
        for (auto& ep : entry_points) {
            auto& file = c.graph.files[ep.source_index].input_file;
            if (auto* repr_ptr = std::get_if<std::shared_ptr<graph::JSRepr>>(&file.repr)) {
                auto& repr = **repr_ptr;
                if (repr.ast.has_lazy_export &&
                    (options->BuildMode == config::Mode::kPassThrough ||
                     (options->BuildMode == config::Mode::kConvertFormat && !config::FormatKeepESMImportExportSyntax(options->OutputFormat)))) {
                    repr.ast.exports_kind = javascript::ExportsKind::kCommonJS;
                }
                if (repr.ast.export_keyword.len > 0 &&
                    (options->OutputFormat == config::Format::kCommonJS ||
                     options->OutputFormat == config::Format::kUMD ||
                     options->OutputFormat == config::Format::kAMD ||
                     options->OutputFormat == config::Format::kSystem ||
                     (options->OutputFormat == config::Format::kIIFE && !options->GlobalName.empty()))) {
                    repr.ast.uses_exports_ref = true;
                    repr.meta.force_include_exports_for_entry_point = true;
                }
            } else if (std::get_if<std::shared_ptr<graph::CopyRepr>>(&file.repr)) {
                additional_files.insert(additional_files.end(),
                    file.additional_files.begin(), file.additional_files.end());
            }
        }

        if (options->OutputFormat == config::Format::kCommonJS ||
            options->OutputFormat == config::Format::kUMD) {
            c.unbound_module_ref = c.graph.GenerateNewSymbol(javascript::kSourceIndex, compiler::SymbolKind::kUnbound, "module");
        } else {
            c.unbound_module_ref = compiler::kInvalidRef;
        }

        if (options->OutputFormat == config::Format::kSystem) {
            c.unbound_exports_ref = c.graph.GenerateNewSymbol(javascript::kSourceIndex, compiler::SymbolKind::kUnbound, "exports");
        } else {
            c.unbound_exports_ref = compiler::kInvalidRef;
        }

        c.ScanImportsAndExports();

        if (c.log.has_errors()) {
            c.options->ExclusiveMangleCacheUpdate([](auto&, auto&) {
            });
            link_guard.done = true;
            timer.End("Link");
            return {};
        }

        c.TreeShakingAndCodeSplitting();

        if (c.options->BuildMode == config::Mode::kPassThrough) {
            for (auto& ep : c.graph.EntryPoints()) {
                c.PreventExportsFromBeingRenamed(ep.source_index);
            }
        }

        c.ComputeChunks();
        c.ComputeCrossChunkDependencies();

        c.timer->Begin("Waiting for mangle cache");
        c.options->ExclusiveMangleCacheUpdate([&](auto& mangle_cache, auto& css_used_local_names) {
            c.timer->End("Waiting for mangle cache");
            c.MangleProps(mangle_cache);
            c.MangleLocalCSS(css_used_local_names);
        });

        compiler::FollowAllSymbols(c.graph.symbols);

        auto result = c.GenerateChunksInParallel(std::move(additional_files));

        result.chunk_metadata.resize(c.chunks.size());
        for (size_t i = 0; i < c.chunks.size(); i++) {
            const ChunkInfo& chunk = c.chunks[i];
            ChunkMetadata& meta = result.chunk_metadata[i];
            meta.source_index = chunk.source_index;
            meta.final_rel_path = chunk.final_rel_path;
            meta.is_entry_point = chunk.is_entry_point;
            meta.is_executable = chunk.is_executable;
            for (const ChunkImport& imp : chunk.cross_chunk_imports) {
                meta.cross_chunk_imports.push_back(imp.chunk_index);
            }
            if (auto* repr = std::get_if<ChunkReprJS>(&chunk.chunk_repr)) {
                if (repr->has_css_chunk && repr->css_chunk_index < c.chunks.size()) {
                    meta.associated_css_rel_path = c.chunks[repr->css_chunk_index].final_rel_path;
                }
            }
        }

        link_guard.done = true;
        timer.End("Link");
        return result;
    }

}
