# ============================================================
# Guchho CTest discovery
#
# Usage:
#
#   guchho_discover_tests(guchho_tests)
#
# Optional:
#
#   guchho_discover_tests(
#       guchho_tests
#       PREFIX "bundler_"
#       WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
#   )
#
# The target must support:
#
#   <test-executable> --list-tests
#   <test-executable> --run=<test-name>
#
# After the target is built, a POST_BUILD command runs
# GuchhoDiscoverTests.cmake to generate one CTest test
# per discovered TEST().
#
# Multi-config generators:
#
#   Visual Studio
#   Xcode
#   Ninja Multi-Config
#
# generate configuration-specific test files and select the
# correct file through CTEST_CONFIGURATION_TYPE at CTest time.
# ============================================================


function(guchho_discover_tests TARGET)

    # --------------------------------------------------------
    # Validate target
    # --------------------------------------------------------

    if(NOT TARGET "${TARGET}")
        message(FATAL_ERROR
            "guchho_discover_tests(): "
            "target '${TARGET}' does not exist"
        )
    endif()


    # --------------------------------------------------------
    # Parse arguments
    # --------------------------------------------------------

    cmake_parse_arguments(
        GDT
        ""
        "PREFIX;WORKING_DIRECTORY"
        ""
        ${ARGN}
    )


    # --------------------------------------------------------
    # Defaults
    # --------------------------------------------------------

    if(NOT DEFINED GDT_PREFIX OR GDT_PREFIX STREQUAL "")
        set(GDT_PREFIX "")
    endif()


    if(NOT DEFINED GDT_WORKING_DIRECTORY OR
       GDT_WORKING_DIRECTORY STREQUAL "")

        set(
            GDT_WORKING_DIRECTORY
            "${CMAKE_CURRENT_BINARY_DIR}"
        )

    endif()


    # --------------------------------------------------------
    # Normalize working directory
    # --------------------------------------------------------

    get_filename_component(
        GDT_WORKING_DIRECTORY
        "${GDT_WORKING_DIRECTORY}"
        ABSOLUTE
    )


    # --------------------------------------------------------
    # Make generated-file names unique
    #
    # Target name alone is normally enough, but hashing keeps
    # the generated filenames safe for unusual target names.
    # --------------------------------------------------------

    string(
        MD5
        gdt_hash
        "${TARGET}"
    )


    set(
        gdt_base
        "${CMAKE_CURRENT_BINARY_DIR}/"
        "${TARGET}_${gdt_hash}"
    )


    # --------------------------------------------------------
    # Detect multi-config generator
    #
    # Examples:
    #
    #   Visual Studio
    #   Xcode
    #   Ninja Multi-Config
    # --------------------------------------------------------

    get_property(
        gdt_multi_config
        GLOBAL
        PROPERTY GENERATOR_IS_MULTI_CONFIG
    )


    # ========================================================
    # Multi-config generators
    # ========================================================

    if(gdt_multi_config)

        # ----------------------------------------------------
        # Dispatcher used by CTest.
        #
        # CTest sets CTEST_CONFIGURATION_TYPE when running
        # tests for a particular configuration.
        # ----------------------------------------------------

        file(
            WRITE
            "${gdt_base}_include.cmake"

            "# Generated by guchho_discover_tests().\n"
            "# Do not edit manually.\n\n"

            "if(DEFINED CTEST_CONFIGURATION_TYPE AND "
            "NOT CTEST_CONFIGURATION_TYPE STREQUAL \"\")\n"

            "    set(_gdt_config "
            "\"\${CTEST_CONFIGURATION_TYPE}\")\n"

            "else()\n"

            "    set(_gdt_config \"\")\n"

            "endif()\n\n"

            "if(EXISTS "
            "\"${gdt_base}_\${_gdt_config}_include.cmake\")\n"

            "    include("
            "\"${gdt_base}_\${_gdt_config}_include.cmake\")\n"

            "else()\n"

            "    add_test(\n"
            "        [=[${GDT_PREFIX}${TARGET}_NOT_BUILT]=]\n"
            "        [==[${TARGET}_NOT_BUILT]==]\n"
            "    )\n"

            "endif()\n"
        )


        # ----------------------------------------------------
        # Generate one dispatcher per configuration.
        # ----------------------------------------------------

        foreach(config IN LISTS CMAKE_CONFIGURATION_TYPES)

            # Configuration names can contain spaces.
            string(
                REPLACE " " "_"
                config_file_name
                "${config}"
            )


            file(
                WRITE
                "${gdt_base}_${config}_include.cmake"

                "# Generated by guchho_discover_tests().\n"
                "# Configuration: ${config}\n"
                "# Do not edit manually.\n\n"

                "if(EXISTS "
                "\"${gdt_base}_${config}_tests.cmake\")\n"

                "    include("
                "\"${gdt_base}_${config}_tests.cmake\")\n"

                "else()\n"

                "    add_test(\n"
                "        [=[${GDT_PREFIX}${TARGET}_NOT_BUILT]=]\n"
                "        [==[${TARGET}_NOT_BUILT]==]\n"
                "    )\n"

                "endif()\n"
            )

        endforeach()


        # ----------------------------------------------------
        # Generator expression selects the configuration file
        # during the build.
        # ----------------------------------------------------

        set(
            gdt_tests_file
            "${gdt_base}_$<CONFIG>_tests.cmake"
        )


    # ========================================================
    # Single-config generators
    # ========================================================

    else()

        file(
            WRITE
            "${gdt_base}_include.cmake"

            "# Generated by guchho_discover_tests().\n"
            "# Do not edit manually.\n\n"

            "if(EXISTS "
            "\"${gdt_base}_tests.cmake\")\n"

            "    include("
            "\"${gdt_base}_tests.cmake\")\n"

            "else()\n"

            "    add_test(\n"
            "        [=[${GDT_PREFIX}${TARGET}_NOT_BUILT]=]\n"
            "        [==[${TARGET}_NOT_BUILT]==]\n"
            "    )\n"

            "endif()\n"
        )


        set(
            gdt_tests_file
            "${gdt_base}_tests.cmake"
        )

    endif()


    # --------------------------------------------------------
    # Tell CTest to include the generated dispatcher.
    # --------------------------------------------------------

    set_property(
        DIRECTORY
        APPEND
        PROPERTY TEST_INCLUDE_FILES
        "${gdt_base}_include.cmake"
    )


    # --------------------------------------------------------
    # Discover tests after the target has been built.
    # --------------------------------------------------------

    add_custom_command(
        TARGET "${TARGET}"
        POST_BUILD

        COMMAND
            "${CMAKE_COMMAND}"

            "-DTEST_EXECUTABLE=$<TARGET_FILE:${TARGET}>"

            "-DTEST_PREFIX=${GDT_PREFIX}"

            "-DTEST_WORKING_DIR=${GDT_WORKING_DIRECTORY}"

            "-DTEST_OUTPUT=${gdt_tests_file}"

            -P
            "${CMAKE_SOURCE_DIR}/cmake/GuchhoDiscoverTests.cmake"

        WORKING_DIRECTORY
            "${CMAKE_CURRENT_BINARY_DIR}"

        VERBATIM

        COMMENT
            "Discovering tests for ${TARGET}"
    )

endfunction()